import { CreateCompanyData, CreateCompanyVariables, CreateTeamData, CreateTeamVariables, CreateWorkerData, CreateWorkerVariables, CreateSiteData, CreateSiteVariables, CreateDailyReportData, CreateDailyReportVariables, CreateDailyReportWorkerData, CreateDailyReportWorkerVariables, UpdateDailyReportWorkerData, UpdateDailyReportWorkerVariables, DeleteDailyReportWorkerData, DeleteDailyReportWorkerVariables, CreatePositionData, CreatePositionVariables, CreateAuditLogData, CreateAuditLogVariables, CreateAgentData, CreateAgentVariables, CreateAgentConversationData, CreateAgentConversationVariables, CreateSettingData, CreateSettingVariables, UpdateSettingData, UpdateSettingVariables, CreateSystemConfigData, CreateSystemConfigVariables, UpdateSystemConfigData, UpdateSystemConfigVariables, DeletePositionData, DeletePositionVariables, UpdateCompanyData, UpdateCompanyVariables, DeleteCompanyData, DeleteCompanyVariables, UpdateTeamData, UpdateTeamVariables, DeleteTeamData, DeleteTeamVariables, UpdateWorkerData, UpdateWorkerVariables, DeleteWorkerData, DeleteWorkerVariables, UpdateSiteData, UpdateSiteVariables, DeleteSiteData, DeleteSiteVariables, UpdateDailyReportData, UpdateDailyReportVariables, DeleteDailyReportData, DeleteDailyReportVariables, CreateAppUserData, CreateAppUserVariables, UpdateAppUserData, UpdateAppUserVariables, DeleteAppUserData, DeleteAppUserVariables, CreateMenuConfigData, CreateMenuConfigVariables, UpdateMenuConfigData, UpdateMenuConfigVariables, DeleteMenuConfigData, DeleteMenuConfigVariables, CreateSystemLogData, CreateSystemLogVariables, CreateAccommodationData, CreateAccommodationVariables, UpdateAccommodationData, UpdateAccommodationVariables, DeleteAccommodationData, DeleteAccommodationVariables, CreateAccommodationAssignmentData, CreateAccommodationAssignmentVariables, UpdateAccommodationAssignmentData, UpdateAccommodationAssignmentVariables, DeleteAccommodationAssignmentData, DeleteAccommodationAssignmentVariables, CreateUtilityRecordData, CreateUtilityRecordVariables, UpdateUtilityRecordData, UpdateUtilityRecordVariables, DeleteUtilityRecordData, DeleteUtilityRecordVariables, CreateAccommodationBillingDocumentData, CreateAccommodationBillingDocumentVariables, UpdateAccommodationBillingDocumentData, UpdateAccommodationBillingDocumentVariables, CreateAccommodationBillingLineItemData, CreateAccommodationBillingLineItemVariables, DeleteAccommodationBillingLineItemData, DeleteAccommodationBillingLineItemVariables, CreateAdvancePaymentData, CreateAdvancePaymentVariables, UpdateAdvancePaymentData, UpdateAdvancePaymentVariables, DeleteAdvancePaymentData, DeleteAdvancePaymentVariables, CreateSmartMemoData, CreateSmartMemoVariables, UpdateSmartMemoData, UpdateSmartMemoVariables, DeleteSmartMemoData, DeleteSmartMemoVariables, CreateSmartMemoCategoryData, CreateSmartMemoCategoryVariables, UpdateSmartMemoCategoryData, UpdateSmartMemoCategoryVariables, DeleteSmartMemoCategoryData, DeleteSmartMemoCategoryVariables, CreateVehicleData, CreateVehicleVariables, UpdateVehicleData, UpdateVehicleVariables, DeleteVehicleData, DeleteVehicleVariables, CreateVehicleAssignmentData, CreateVehicleAssignmentVariables, UpdateVehicleAssignmentData, UpdateVehicleAssignmentVariables, DeleteVehicleAssignmentData, DeleteVehicleAssignmentVariables, CreateVehicleExpenseData, CreateVehicleExpenseVariables, UpdateVehicleExpenseData, UpdateVehicleExpenseVariables, DeleteVehicleExpenseData, DeleteVehicleExpenseVariables, CreateVehicleBillingDocumentData, CreateVehicleBillingDocumentVariables, UpdateVehicleBillingDocumentData, UpdateVehicleBillingDocumentVariables, DeleteVehicleBillingDocumentData, DeleteVehicleBillingDocumentVariables, UpdateAgentData, UpdateAgentVariables, UpdateAgentConversationData, UpdateAgentConversationVariables, CreateDailyDispatchData, CreateDailyDispatchVariables, UpdateDailyDispatchData, UpdateDailyDispatchVariables, DeleteDailyDispatchData, DeleteDailyDispatchVariables, CreatePaymentData, CreatePaymentVariables, UpdatePaymentData, UpdatePaymentVariables, DeletePaymentData, DeletePaymentVariables, CreateTaxInvoiceData, CreateTaxInvoiceVariables, UpdateTaxInvoiceData, UpdateTaxInvoiceVariables, DeleteTaxInvoiceData, DeleteTaxInvoiceVariables, CreateReceivableData, CreateReceivableVariables, UpdateReceivableData, UpdateReceivableVariables, DeleteReceivableData, DeleteReceivableVariables, ListCompaniesData, GetCompanyData, GetCompanyVariables, ListTeamsData, GetTeamData, GetTeamVariables, ListWorkersData, ListPositionsData, GetWorkerData, GetWorkerVariables, ListSitesData, GetSiteData, GetSiteVariables, ListDailyReportsData, ListDailyReportWorkersData, ListAppUsersData, ListMenuConfigsData, ListSystemLogsData, ListAuditLogsData, ListAgentsData, ListAgentConversationsData, ListSettingsData, ListSystemConfigsData, ListAllCompaniesData, ListAllCompaniesVariables, ListAllTeamsData, ListAllTeamsVariables, ListAllWorkersData, ListAllWorkersVariables, ListAllPositionsData, ListAllPositionsVariables, ListAllSitesData, ListAllSitesVariables, ListAllDailyReportsData, ListAllDailyReportsVariables, ListAllDailyReportWorkersData, ListAllDailyReportWorkersVariables, ListAllAppUsersData, ListAllAppUsersVariables, ListAllMenuConfigsData, ListAllMenuConfigsVariables, ListAllSystemLogsData, ListAllSystemLogsVariables, ListAllAuditLogsData, ListAllAuditLogsVariables, ListAllAgentsData, ListAllAgentsVariables, ListAllAgentConversationsData, ListAllAgentConversationsVariables, ListAllSettingsData, ListAllSettingsVariables, ListAllSystemConfigsData, ListAllSystemConfigsVariables, ListAllAccommodationsData, ListAllAccommodationsVariables, ListAllAccommodationAssignmentsData, ListAllAccommodationAssignmentsVariables, ListAllUtilityRecordsData, ListAllUtilityRecordsVariables, ListAllAccommodationBillingDocumentsData, ListAllAccommodationBillingDocumentsVariables, ListAllAccommodationBillingLineItemsData, ListAllAccommodationBillingLineItemsVariables, ListAllAdvancePaymentsData, ListAllAdvancePaymentsVariables, ListAllSmartMemoCategoriesData, ListAllSmartMemoCategoriesVariables, ListAllSmartMemosData, ListAllSmartMemosVariables, ListAllVehiclesData, ListAllVehiclesVariables, ListAllVehicleAssignmentsData, ListAllVehicleAssignmentsVariables, ListAllVehicleExpensesData, ListAllVehicleExpensesVariables, ListAllVehicleBillingDocumentsData, ListAllVehicleBillingDocumentsVariables, ListAllDailyDispatchesData, ListAllDailyDispatchesVariables, ListAllPaymentsData, ListAllPaymentsVariables, ListAllTaxInvoicesData, ListAllTaxInvoicesVariables, ListAllReceivablesData, ListAllReceivablesVariables } from '../';
import { UseDataConnectQueryResult, useDataConnectQueryOptions, UseDataConnectMutationResult, useDataConnectMutationOptions} from '@tanstack-query-firebase/react/data-connect';
import { UseQueryResult, UseMutationResult} from '@tanstack/react-query';
import { DataConnect } from 'firebase/data-connect';
import { FirebaseError } from 'firebase/app';


export function useCreateCompany(options?: useDataConnectMutationOptions<CreateCompanyData, FirebaseError, CreateCompanyVariables>): UseDataConnectMutationResult<CreateCompanyData, CreateCompanyVariables>;
export function useCreateCompany(dc: DataConnect, options?: useDataConnectMutationOptions<CreateCompanyData, FirebaseError, CreateCompanyVariables>): UseDataConnectMutationResult<CreateCompanyData, CreateCompanyVariables>;

export function useCreateTeam(options?: useDataConnectMutationOptions<CreateTeamData, FirebaseError, CreateTeamVariables>): UseDataConnectMutationResult<CreateTeamData, CreateTeamVariables>;
export function useCreateTeam(dc: DataConnect, options?: useDataConnectMutationOptions<CreateTeamData, FirebaseError, CreateTeamVariables>): UseDataConnectMutationResult<CreateTeamData, CreateTeamVariables>;

export function useCreateWorker(options?: useDataConnectMutationOptions<CreateWorkerData, FirebaseError, CreateWorkerVariables>): UseDataConnectMutationResult<CreateWorkerData, CreateWorkerVariables>;
export function useCreateWorker(dc: DataConnect, options?: useDataConnectMutationOptions<CreateWorkerData, FirebaseError, CreateWorkerVariables>): UseDataConnectMutationResult<CreateWorkerData, CreateWorkerVariables>;

export function useCreateSite(options?: useDataConnectMutationOptions<CreateSiteData, FirebaseError, CreateSiteVariables>): UseDataConnectMutationResult<CreateSiteData, CreateSiteVariables>;
export function useCreateSite(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSiteData, FirebaseError, CreateSiteVariables>): UseDataConnectMutationResult<CreateSiteData, CreateSiteVariables>;

export function useCreateDailyReport(options?: useDataConnectMutationOptions<CreateDailyReportData, FirebaseError, CreateDailyReportVariables>): UseDataConnectMutationResult<CreateDailyReportData, CreateDailyReportVariables>;
export function useCreateDailyReport(dc: DataConnect, options?: useDataConnectMutationOptions<CreateDailyReportData, FirebaseError, CreateDailyReportVariables>): UseDataConnectMutationResult<CreateDailyReportData, CreateDailyReportVariables>;

export function useCreateDailyReportWorker(options?: useDataConnectMutationOptions<CreateDailyReportWorkerData, FirebaseError, CreateDailyReportWorkerVariables>): UseDataConnectMutationResult<CreateDailyReportWorkerData, CreateDailyReportWorkerVariables>;
export function useCreateDailyReportWorker(dc: DataConnect, options?: useDataConnectMutationOptions<CreateDailyReportWorkerData, FirebaseError, CreateDailyReportWorkerVariables>): UseDataConnectMutationResult<CreateDailyReportWorkerData, CreateDailyReportWorkerVariables>;

export function useUpdateDailyReportWorker(options?: useDataConnectMutationOptions<UpdateDailyReportWorkerData, FirebaseError, UpdateDailyReportWorkerVariables>): UseDataConnectMutationResult<UpdateDailyReportWorkerData, UpdateDailyReportWorkerVariables>;
export function useUpdateDailyReportWorker(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateDailyReportWorkerData, FirebaseError, UpdateDailyReportWorkerVariables>): UseDataConnectMutationResult<UpdateDailyReportWorkerData, UpdateDailyReportWorkerVariables>;

export function useDeleteDailyReportWorker(options?: useDataConnectMutationOptions<DeleteDailyReportWorkerData, FirebaseError, DeleteDailyReportWorkerVariables>): UseDataConnectMutationResult<DeleteDailyReportWorkerData, DeleteDailyReportWorkerVariables>;
export function useDeleteDailyReportWorker(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteDailyReportWorkerData, FirebaseError, DeleteDailyReportWorkerVariables>): UseDataConnectMutationResult<DeleteDailyReportWorkerData, DeleteDailyReportWorkerVariables>;

export function useCreatePosition(options?: useDataConnectMutationOptions<CreatePositionData, FirebaseError, CreatePositionVariables>): UseDataConnectMutationResult<CreatePositionData, CreatePositionVariables>;
export function useCreatePosition(dc: DataConnect, options?: useDataConnectMutationOptions<CreatePositionData, FirebaseError, CreatePositionVariables>): UseDataConnectMutationResult<CreatePositionData, CreatePositionVariables>;

export function useCreateAuditLog(options?: useDataConnectMutationOptions<CreateAuditLogData, FirebaseError, CreateAuditLogVariables>): UseDataConnectMutationResult<CreateAuditLogData, CreateAuditLogVariables>;
export function useCreateAuditLog(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAuditLogData, FirebaseError, CreateAuditLogVariables>): UseDataConnectMutationResult<CreateAuditLogData, CreateAuditLogVariables>;

export function useCreateAgent(options?: useDataConnectMutationOptions<CreateAgentData, FirebaseError, CreateAgentVariables>): UseDataConnectMutationResult<CreateAgentData, CreateAgentVariables>;
export function useCreateAgent(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAgentData, FirebaseError, CreateAgentVariables>): UseDataConnectMutationResult<CreateAgentData, CreateAgentVariables>;

export function useCreateAgentConversation(options?: useDataConnectMutationOptions<CreateAgentConversationData, FirebaseError, CreateAgentConversationVariables>): UseDataConnectMutationResult<CreateAgentConversationData, CreateAgentConversationVariables>;
export function useCreateAgentConversation(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAgentConversationData, FirebaseError, CreateAgentConversationVariables>): UseDataConnectMutationResult<CreateAgentConversationData, CreateAgentConversationVariables>;

export function useCreateSetting(options?: useDataConnectMutationOptions<CreateSettingData, FirebaseError, CreateSettingVariables>): UseDataConnectMutationResult<CreateSettingData, CreateSettingVariables>;
export function useCreateSetting(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSettingData, FirebaseError, CreateSettingVariables>): UseDataConnectMutationResult<CreateSettingData, CreateSettingVariables>;

export function useUpdateSetting(options?: useDataConnectMutationOptions<UpdateSettingData, FirebaseError, UpdateSettingVariables>): UseDataConnectMutationResult<UpdateSettingData, UpdateSettingVariables>;
export function useUpdateSetting(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateSettingData, FirebaseError, UpdateSettingVariables>): UseDataConnectMutationResult<UpdateSettingData, UpdateSettingVariables>;

export function useCreateSystemConfig(options?: useDataConnectMutationOptions<CreateSystemConfigData, FirebaseError, CreateSystemConfigVariables>): UseDataConnectMutationResult<CreateSystemConfigData, CreateSystemConfigVariables>;
export function useCreateSystemConfig(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSystemConfigData, FirebaseError, CreateSystemConfigVariables>): UseDataConnectMutationResult<CreateSystemConfigData, CreateSystemConfigVariables>;

export function useUpdateSystemConfig(options?: useDataConnectMutationOptions<UpdateSystemConfigData, FirebaseError, UpdateSystemConfigVariables>): UseDataConnectMutationResult<UpdateSystemConfigData, UpdateSystemConfigVariables>;
export function useUpdateSystemConfig(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateSystemConfigData, FirebaseError, UpdateSystemConfigVariables>): UseDataConnectMutationResult<UpdateSystemConfigData, UpdateSystemConfigVariables>;

export function useDeletePosition(options?: useDataConnectMutationOptions<DeletePositionData, FirebaseError, DeletePositionVariables>): UseDataConnectMutationResult<DeletePositionData, DeletePositionVariables>;
export function useDeletePosition(dc: DataConnect, options?: useDataConnectMutationOptions<DeletePositionData, FirebaseError, DeletePositionVariables>): UseDataConnectMutationResult<DeletePositionData, DeletePositionVariables>;

export function useUpdateCompany(options?: useDataConnectMutationOptions<UpdateCompanyData, FirebaseError, UpdateCompanyVariables>): UseDataConnectMutationResult<UpdateCompanyData, UpdateCompanyVariables>;
export function useUpdateCompany(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateCompanyData, FirebaseError, UpdateCompanyVariables>): UseDataConnectMutationResult<UpdateCompanyData, UpdateCompanyVariables>;

export function useDeleteCompany(options?: useDataConnectMutationOptions<DeleteCompanyData, FirebaseError, DeleteCompanyVariables>): UseDataConnectMutationResult<DeleteCompanyData, DeleteCompanyVariables>;
export function useDeleteCompany(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteCompanyData, FirebaseError, DeleteCompanyVariables>): UseDataConnectMutationResult<DeleteCompanyData, DeleteCompanyVariables>;

export function useUpdateTeam(options?: useDataConnectMutationOptions<UpdateTeamData, FirebaseError, UpdateTeamVariables>): UseDataConnectMutationResult<UpdateTeamData, UpdateTeamVariables>;
export function useUpdateTeam(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateTeamData, FirebaseError, UpdateTeamVariables>): UseDataConnectMutationResult<UpdateTeamData, UpdateTeamVariables>;

export function useDeleteTeam(options?: useDataConnectMutationOptions<DeleteTeamData, FirebaseError, DeleteTeamVariables>): UseDataConnectMutationResult<DeleteTeamData, DeleteTeamVariables>;
export function useDeleteTeam(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteTeamData, FirebaseError, DeleteTeamVariables>): UseDataConnectMutationResult<DeleteTeamData, DeleteTeamVariables>;

export function useUpdateWorker(options?: useDataConnectMutationOptions<UpdateWorkerData, FirebaseError, UpdateWorkerVariables>): UseDataConnectMutationResult<UpdateWorkerData, UpdateWorkerVariables>;
export function useUpdateWorker(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateWorkerData, FirebaseError, UpdateWorkerVariables>): UseDataConnectMutationResult<UpdateWorkerData, UpdateWorkerVariables>;

export function useDeleteWorker(options?: useDataConnectMutationOptions<DeleteWorkerData, FirebaseError, DeleteWorkerVariables>): UseDataConnectMutationResult<DeleteWorkerData, DeleteWorkerVariables>;
export function useDeleteWorker(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteWorkerData, FirebaseError, DeleteWorkerVariables>): UseDataConnectMutationResult<DeleteWorkerData, DeleteWorkerVariables>;

export function useUpdateSite(options?: useDataConnectMutationOptions<UpdateSiteData, FirebaseError, UpdateSiteVariables>): UseDataConnectMutationResult<UpdateSiteData, UpdateSiteVariables>;
export function useUpdateSite(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateSiteData, FirebaseError, UpdateSiteVariables>): UseDataConnectMutationResult<UpdateSiteData, UpdateSiteVariables>;

export function useDeleteSite(options?: useDataConnectMutationOptions<DeleteSiteData, FirebaseError, DeleteSiteVariables>): UseDataConnectMutationResult<DeleteSiteData, DeleteSiteVariables>;
export function useDeleteSite(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteSiteData, FirebaseError, DeleteSiteVariables>): UseDataConnectMutationResult<DeleteSiteData, DeleteSiteVariables>;

export function useUpdateDailyReport(options?: useDataConnectMutationOptions<UpdateDailyReportData, FirebaseError, UpdateDailyReportVariables>): UseDataConnectMutationResult<UpdateDailyReportData, UpdateDailyReportVariables>;
export function useUpdateDailyReport(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateDailyReportData, FirebaseError, UpdateDailyReportVariables>): UseDataConnectMutationResult<UpdateDailyReportData, UpdateDailyReportVariables>;

export function useDeleteDailyReport(options?: useDataConnectMutationOptions<DeleteDailyReportData, FirebaseError, DeleteDailyReportVariables>): UseDataConnectMutationResult<DeleteDailyReportData, DeleteDailyReportVariables>;
export function useDeleteDailyReport(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteDailyReportData, FirebaseError, DeleteDailyReportVariables>): UseDataConnectMutationResult<DeleteDailyReportData, DeleteDailyReportVariables>;

export function useCreateAppUser(options?: useDataConnectMutationOptions<CreateAppUserData, FirebaseError, CreateAppUserVariables>): UseDataConnectMutationResult<CreateAppUserData, CreateAppUserVariables>;
export function useCreateAppUser(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAppUserData, FirebaseError, CreateAppUserVariables>): UseDataConnectMutationResult<CreateAppUserData, CreateAppUserVariables>;

export function useUpdateAppUser(options?: useDataConnectMutationOptions<UpdateAppUserData, FirebaseError, UpdateAppUserVariables>): UseDataConnectMutationResult<UpdateAppUserData, UpdateAppUserVariables>;
export function useUpdateAppUser(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateAppUserData, FirebaseError, UpdateAppUserVariables>): UseDataConnectMutationResult<UpdateAppUserData, UpdateAppUserVariables>;

export function useDeleteAppUser(options?: useDataConnectMutationOptions<DeleteAppUserData, FirebaseError, DeleteAppUserVariables>): UseDataConnectMutationResult<DeleteAppUserData, DeleteAppUserVariables>;
export function useDeleteAppUser(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteAppUserData, FirebaseError, DeleteAppUserVariables>): UseDataConnectMutationResult<DeleteAppUserData, DeleteAppUserVariables>;

export function useCreateMenuConfig(options?: useDataConnectMutationOptions<CreateMenuConfigData, FirebaseError, CreateMenuConfigVariables>): UseDataConnectMutationResult<CreateMenuConfigData, CreateMenuConfigVariables>;
export function useCreateMenuConfig(dc: DataConnect, options?: useDataConnectMutationOptions<CreateMenuConfigData, FirebaseError, CreateMenuConfigVariables>): UseDataConnectMutationResult<CreateMenuConfigData, CreateMenuConfigVariables>;

export function useUpdateMenuConfig(options?: useDataConnectMutationOptions<UpdateMenuConfigData, FirebaseError, UpdateMenuConfigVariables>): UseDataConnectMutationResult<UpdateMenuConfigData, UpdateMenuConfigVariables>;
export function useUpdateMenuConfig(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateMenuConfigData, FirebaseError, UpdateMenuConfigVariables>): UseDataConnectMutationResult<UpdateMenuConfigData, UpdateMenuConfigVariables>;

export function useDeleteMenuConfig(options?: useDataConnectMutationOptions<DeleteMenuConfigData, FirebaseError, DeleteMenuConfigVariables>): UseDataConnectMutationResult<DeleteMenuConfigData, DeleteMenuConfigVariables>;
export function useDeleteMenuConfig(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteMenuConfigData, FirebaseError, DeleteMenuConfigVariables>): UseDataConnectMutationResult<DeleteMenuConfigData, DeleteMenuConfigVariables>;

export function useCreateSystemLog(options?: useDataConnectMutationOptions<CreateSystemLogData, FirebaseError, CreateSystemLogVariables>): UseDataConnectMutationResult<CreateSystemLogData, CreateSystemLogVariables>;
export function useCreateSystemLog(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSystemLogData, FirebaseError, CreateSystemLogVariables>): UseDataConnectMutationResult<CreateSystemLogData, CreateSystemLogVariables>;

export function useCreateAccommodation(options?: useDataConnectMutationOptions<CreateAccommodationData, FirebaseError, CreateAccommodationVariables>): UseDataConnectMutationResult<CreateAccommodationData, CreateAccommodationVariables>;
export function useCreateAccommodation(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAccommodationData, FirebaseError, CreateAccommodationVariables>): UseDataConnectMutationResult<CreateAccommodationData, CreateAccommodationVariables>;

export function useUpdateAccommodation(options?: useDataConnectMutationOptions<UpdateAccommodationData, FirebaseError, UpdateAccommodationVariables>): UseDataConnectMutationResult<UpdateAccommodationData, UpdateAccommodationVariables>;
export function useUpdateAccommodation(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateAccommodationData, FirebaseError, UpdateAccommodationVariables>): UseDataConnectMutationResult<UpdateAccommodationData, UpdateAccommodationVariables>;

export function useDeleteAccommodation(options?: useDataConnectMutationOptions<DeleteAccommodationData, FirebaseError, DeleteAccommodationVariables>): UseDataConnectMutationResult<DeleteAccommodationData, DeleteAccommodationVariables>;
export function useDeleteAccommodation(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteAccommodationData, FirebaseError, DeleteAccommodationVariables>): UseDataConnectMutationResult<DeleteAccommodationData, DeleteAccommodationVariables>;

export function useCreateAccommodationAssignment(options?: useDataConnectMutationOptions<CreateAccommodationAssignmentData, FirebaseError, CreateAccommodationAssignmentVariables>): UseDataConnectMutationResult<CreateAccommodationAssignmentData, CreateAccommodationAssignmentVariables>;
export function useCreateAccommodationAssignment(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAccommodationAssignmentData, FirebaseError, CreateAccommodationAssignmentVariables>): UseDataConnectMutationResult<CreateAccommodationAssignmentData, CreateAccommodationAssignmentVariables>;

export function useUpdateAccommodationAssignment(options?: useDataConnectMutationOptions<UpdateAccommodationAssignmentData, FirebaseError, UpdateAccommodationAssignmentVariables>): UseDataConnectMutationResult<UpdateAccommodationAssignmentData, UpdateAccommodationAssignmentVariables>;
export function useUpdateAccommodationAssignment(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateAccommodationAssignmentData, FirebaseError, UpdateAccommodationAssignmentVariables>): UseDataConnectMutationResult<UpdateAccommodationAssignmentData, UpdateAccommodationAssignmentVariables>;

export function useDeleteAccommodationAssignment(options?: useDataConnectMutationOptions<DeleteAccommodationAssignmentData, FirebaseError, DeleteAccommodationAssignmentVariables>): UseDataConnectMutationResult<DeleteAccommodationAssignmentData, DeleteAccommodationAssignmentVariables>;
export function useDeleteAccommodationAssignment(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteAccommodationAssignmentData, FirebaseError, DeleteAccommodationAssignmentVariables>): UseDataConnectMutationResult<DeleteAccommodationAssignmentData, DeleteAccommodationAssignmentVariables>;

export function useCreateUtilityRecord(options?: useDataConnectMutationOptions<CreateUtilityRecordData, FirebaseError, CreateUtilityRecordVariables>): UseDataConnectMutationResult<CreateUtilityRecordData, CreateUtilityRecordVariables>;
export function useCreateUtilityRecord(dc: DataConnect, options?: useDataConnectMutationOptions<CreateUtilityRecordData, FirebaseError, CreateUtilityRecordVariables>): UseDataConnectMutationResult<CreateUtilityRecordData, CreateUtilityRecordVariables>;

export function useUpdateUtilityRecord(options?: useDataConnectMutationOptions<UpdateUtilityRecordData, FirebaseError, UpdateUtilityRecordVariables>): UseDataConnectMutationResult<UpdateUtilityRecordData, UpdateUtilityRecordVariables>;
export function useUpdateUtilityRecord(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateUtilityRecordData, FirebaseError, UpdateUtilityRecordVariables>): UseDataConnectMutationResult<UpdateUtilityRecordData, UpdateUtilityRecordVariables>;

export function useDeleteUtilityRecord(options?: useDataConnectMutationOptions<DeleteUtilityRecordData, FirebaseError, DeleteUtilityRecordVariables>): UseDataConnectMutationResult<DeleteUtilityRecordData, DeleteUtilityRecordVariables>;
export function useDeleteUtilityRecord(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteUtilityRecordData, FirebaseError, DeleteUtilityRecordVariables>): UseDataConnectMutationResult<DeleteUtilityRecordData, DeleteUtilityRecordVariables>;

export function useCreateAccommodationBillingDocument(options?: useDataConnectMutationOptions<CreateAccommodationBillingDocumentData, FirebaseError, CreateAccommodationBillingDocumentVariables>): UseDataConnectMutationResult<CreateAccommodationBillingDocumentData, CreateAccommodationBillingDocumentVariables>;
export function useCreateAccommodationBillingDocument(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAccommodationBillingDocumentData, FirebaseError, CreateAccommodationBillingDocumentVariables>): UseDataConnectMutationResult<CreateAccommodationBillingDocumentData, CreateAccommodationBillingDocumentVariables>;

export function useUpdateAccommodationBillingDocument(options?: useDataConnectMutationOptions<UpdateAccommodationBillingDocumentData, FirebaseError, UpdateAccommodationBillingDocumentVariables>): UseDataConnectMutationResult<UpdateAccommodationBillingDocumentData, UpdateAccommodationBillingDocumentVariables>;
export function useUpdateAccommodationBillingDocument(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateAccommodationBillingDocumentData, FirebaseError, UpdateAccommodationBillingDocumentVariables>): UseDataConnectMutationResult<UpdateAccommodationBillingDocumentData, UpdateAccommodationBillingDocumentVariables>;

export function useCreateAccommodationBillingLineItem(options?: useDataConnectMutationOptions<CreateAccommodationBillingLineItemData, FirebaseError, CreateAccommodationBillingLineItemVariables>): UseDataConnectMutationResult<CreateAccommodationBillingLineItemData, CreateAccommodationBillingLineItemVariables>;
export function useCreateAccommodationBillingLineItem(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAccommodationBillingLineItemData, FirebaseError, CreateAccommodationBillingLineItemVariables>): UseDataConnectMutationResult<CreateAccommodationBillingLineItemData, CreateAccommodationBillingLineItemVariables>;

export function useDeleteAccommodationBillingLineItem(options?: useDataConnectMutationOptions<DeleteAccommodationBillingLineItemData, FirebaseError, DeleteAccommodationBillingLineItemVariables>): UseDataConnectMutationResult<DeleteAccommodationBillingLineItemData, DeleteAccommodationBillingLineItemVariables>;
export function useDeleteAccommodationBillingLineItem(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteAccommodationBillingLineItemData, FirebaseError, DeleteAccommodationBillingLineItemVariables>): UseDataConnectMutationResult<DeleteAccommodationBillingLineItemData, DeleteAccommodationBillingLineItemVariables>;

export function useCreateAdvancePayment(options?: useDataConnectMutationOptions<CreateAdvancePaymentData, FirebaseError, CreateAdvancePaymentVariables>): UseDataConnectMutationResult<CreateAdvancePaymentData, CreateAdvancePaymentVariables>;
export function useCreateAdvancePayment(dc: DataConnect, options?: useDataConnectMutationOptions<CreateAdvancePaymentData, FirebaseError, CreateAdvancePaymentVariables>): UseDataConnectMutationResult<CreateAdvancePaymentData, CreateAdvancePaymentVariables>;

export function useUpdateAdvancePayment(options?: useDataConnectMutationOptions<UpdateAdvancePaymentData, FirebaseError, UpdateAdvancePaymentVariables>): UseDataConnectMutationResult<UpdateAdvancePaymentData, UpdateAdvancePaymentVariables>;
export function useUpdateAdvancePayment(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateAdvancePaymentData, FirebaseError, UpdateAdvancePaymentVariables>): UseDataConnectMutationResult<UpdateAdvancePaymentData, UpdateAdvancePaymentVariables>;

export function useDeleteAdvancePayment(options?: useDataConnectMutationOptions<DeleteAdvancePaymentData, FirebaseError, DeleteAdvancePaymentVariables>): UseDataConnectMutationResult<DeleteAdvancePaymentData, DeleteAdvancePaymentVariables>;
export function useDeleteAdvancePayment(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteAdvancePaymentData, FirebaseError, DeleteAdvancePaymentVariables>): UseDataConnectMutationResult<DeleteAdvancePaymentData, DeleteAdvancePaymentVariables>;

export function useCreateSmartMemo(options?: useDataConnectMutationOptions<CreateSmartMemoData, FirebaseError, CreateSmartMemoVariables>): UseDataConnectMutationResult<CreateSmartMemoData, CreateSmartMemoVariables>;
export function useCreateSmartMemo(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSmartMemoData, FirebaseError, CreateSmartMemoVariables>): UseDataConnectMutationResult<CreateSmartMemoData, CreateSmartMemoVariables>;

export function useUpdateSmartMemo(options?: useDataConnectMutationOptions<UpdateSmartMemoData, FirebaseError, UpdateSmartMemoVariables>): UseDataConnectMutationResult<UpdateSmartMemoData, UpdateSmartMemoVariables>;
export function useUpdateSmartMemo(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateSmartMemoData, FirebaseError, UpdateSmartMemoVariables>): UseDataConnectMutationResult<UpdateSmartMemoData, UpdateSmartMemoVariables>;

export function useDeleteSmartMemo(options?: useDataConnectMutationOptions<DeleteSmartMemoData, FirebaseError, DeleteSmartMemoVariables>): UseDataConnectMutationResult<DeleteSmartMemoData, DeleteSmartMemoVariables>;
export function useDeleteSmartMemo(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteSmartMemoData, FirebaseError, DeleteSmartMemoVariables>): UseDataConnectMutationResult<DeleteSmartMemoData, DeleteSmartMemoVariables>;

export function useCreateSmartMemoCategory(options?: useDataConnectMutationOptions<CreateSmartMemoCategoryData, FirebaseError, CreateSmartMemoCategoryVariables>): UseDataConnectMutationResult<CreateSmartMemoCategoryData, CreateSmartMemoCategoryVariables>;
export function useCreateSmartMemoCategory(dc: DataConnect, options?: useDataConnectMutationOptions<CreateSmartMemoCategoryData, FirebaseError, CreateSmartMemoCategoryVariables>): UseDataConnectMutationResult<CreateSmartMemoCategoryData, CreateSmartMemoCategoryVariables>;

export function useUpdateSmartMemoCategory(options?: useDataConnectMutationOptions<UpdateSmartMemoCategoryData, FirebaseError, UpdateSmartMemoCategoryVariables>): UseDataConnectMutationResult<UpdateSmartMemoCategoryData, UpdateSmartMemoCategoryVariables>;
export function useUpdateSmartMemoCategory(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateSmartMemoCategoryData, FirebaseError, UpdateSmartMemoCategoryVariables>): UseDataConnectMutationResult<UpdateSmartMemoCategoryData, UpdateSmartMemoCategoryVariables>;

export function useDeleteSmartMemoCategory(options?: useDataConnectMutationOptions<DeleteSmartMemoCategoryData, FirebaseError, DeleteSmartMemoCategoryVariables>): UseDataConnectMutationResult<DeleteSmartMemoCategoryData, DeleteSmartMemoCategoryVariables>;
export function useDeleteSmartMemoCategory(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteSmartMemoCategoryData, FirebaseError, DeleteSmartMemoCategoryVariables>): UseDataConnectMutationResult<DeleteSmartMemoCategoryData, DeleteSmartMemoCategoryVariables>;

export function useCreateVehicle(options?: useDataConnectMutationOptions<CreateVehicleData, FirebaseError, CreateVehicleVariables>): UseDataConnectMutationResult<CreateVehicleData, CreateVehicleVariables>;
export function useCreateVehicle(dc: DataConnect, options?: useDataConnectMutationOptions<CreateVehicleData, FirebaseError, CreateVehicleVariables>): UseDataConnectMutationResult<CreateVehicleData, CreateVehicleVariables>;

export function useUpdateVehicle(options?: useDataConnectMutationOptions<UpdateVehicleData, FirebaseError, UpdateVehicleVariables>): UseDataConnectMutationResult<UpdateVehicleData, UpdateVehicleVariables>;
export function useUpdateVehicle(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateVehicleData, FirebaseError, UpdateVehicleVariables>): UseDataConnectMutationResult<UpdateVehicleData, UpdateVehicleVariables>;

export function useDeleteVehicle(options?: useDataConnectMutationOptions<DeleteVehicleData, FirebaseError, DeleteVehicleVariables>): UseDataConnectMutationResult<DeleteVehicleData, DeleteVehicleVariables>;
export function useDeleteVehicle(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteVehicleData, FirebaseError, DeleteVehicleVariables>): UseDataConnectMutationResult<DeleteVehicleData, DeleteVehicleVariables>;

export function useCreateVehicleAssignment(options?: useDataConnectMutationOptions<CreateVehicleAssignmentData, FirebaseError, CreateVehicleAssignmentVariables>): UseDataConnectMutationResult<CreateVehicleAssignmentData, CreateVehicleAssignmentVariables>;
export function useCreateVehicleAssignment(dc: DataConnect, options?: useDataConnectMutationOptions<CreateVehicleAssignmentData, FirebaseError, CreateVehicleAssignmentVariables>): UseDataConnectMutationResult<CreateVehicleAssignmentData, CreateVehicleAssignmentVariables>;

export function useUpdateVehicleAssignment(options?: useDataConnectMutationOptions<UpdateVehicleAssignmentData, FirebaseError, UpdateVehicleAssignmentVariables>): UseDataConnectMutationResult<UpdateVehicleAssignmentData, UpdateVehicleAssignmentVariables>;
export function useUpdateVehicleAssignment(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateVehicleAssignmentData, FirebaseError, UpdateVehicleAssignmentVariables>): UseDataConnectMutationResult<UpdateVehicleAssignmentData, UpdateVehicleAssignmentVariables>;

export function useDeleteVehicleAssignment(options?: useDataConnectMutationOptions<DeleteVehicleAssignmentData, FirebaseError, DeleteVehicleAssignmentVariables>): UseDataConnectMutationResult<DeleteVehicleAssignmentData, DeleteVehicleAssignmentVariables>;
export function useDeleteVehicleAssignment(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteVehicleAssignmentData, FirebaseError, DeleteVehicleAssignmentVariables>): UseDataConnectMutationResult<DeleteVehicleAssignmentData, DeleteVehicleAssignmentVariables>;

export function useCreateVehicleExpense(options?: useDataConnectMutationOptions<CreateVehicleExpenseData, FirebaseError, CreateVehicleExpenseVariables>): UseDataConnectMutationResult<CreateVehicleExpenseData, CreateVehicleExpenseVariables>;
export function useCreateVehicleExpense(dc: DataConnect, options?: useDataConnectMutationOptions<CreateVehicleExpenseData, FirebaseError, CreateVehicleExpenseVariables>): UseDataConnectMutationResult<CreateVehicleExpenseData, CreateVehicleExpenseVariables>;

export function useUpdateVehicleExpense(options?: useDataConnectMutationOptions<UpdateVehicleExpenseData, FirebaseError, UpdateVehicleExpenseVariables>): UseDataConnectMutationResult<UpdateVehicleExpenseData, UpdateVehicleExpenseVariables>;
export function useUpdateVehicleExpense(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateVehicleExpenseData, FirebaseError, UpdateVehicleExpenseVariables>): UseDataConnectMutationResult<UpdateVehicleExpenseData, UpdateVehicleExpenseVariables>;

export function useDeleteVehicleExpense(options?: useDataConnectMutationOptions<DeleteVehicleExpenseData, FirebaseError, DeleteVehicleExpenseVariables>): UseDataConnectMutationResult<DeleteVehicleExpenseData, DeleteVehicleExpenseVariables>;
export function useDeleteVehicleExpense(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteVehicleExpenseData, FirebaseError, DeleteVehicleExpenseVariables>): UseDataConnectMutationResult<DeleteVehicleExpenseData, DeleteVehicleExpenseVariables>;

export function useCreateVehicleBillingDocument(options?: useDataConnectMutationOptions<CreateVehicleBillingDocumentData, FirebaseError, CreateVehicleBillingDocumentVariables>): UseDataConnectMutationResult<CreateVehicleBillingDocumentData, CreateVehicleBillingDocumentVariables>;
export function useCreateVehicleBillingDocument(dc: DataConnect, options?: useDataConnectMutationOptions<CreateVehicleBillingDocumentData, FirebaseError, CreateVehicleBillingDocumentVariables>): UseDataConnectMutationResult<CreateVehicleBillingDocumentData, CreateVehicleBillingDocumentVariables>;

export function useUpdateVehicleBillingDocument(options?: useDataConnectMutationOptions<UpdateVehicleBillingDocumentData, FirebaseError, UpdateVehicleBillingDocumentVariables>): UseDataConnectMutationResult<UpdateVehicleBillingDocumentData, UpdateVehicleBillingDocumentVariables>;
export function useUpdateVehicleBillingDocument(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateVehicleBillingDocumentData, FirebaseError, UpdateVehicleBillingDocumentVariables>): UseDataConnectMutationResult<UpdateVehicleBillingDocumentData, UpdateVehicleBillingDocumentVariables>;

export function useDeleteVehicleBillingDocument(options?: useDataConnectMutationOptions<DeleteVehicleBillingDocumentData, FirebaseError, DeleteVehicleBillingDocumentVariables>): UseDataConnectMutationResult<DeleteVehicleBillingDocumentData, DeleteVehicleBillingDocumentVariables>;
export function useDeleteVehicleBillingDocument(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteVehicleBillingDocumentData, FirebaseError, DeleteVehicleBillingDocumentVariables>): UseDataConnectMutationResult<DeleteVehicleBillingDocumentData, DeleteVehicleBillingDocumentVariables>;

export function useUpdateAgent(options?: useDataConnectMutationOptions<UpdateAgentData, FirebaseError, UpdateAgentVariables>): UseDataConnectMutationResult<UpdateAgentData, UpdateAgentVariables>;
export function useUpdateAgent(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateAgentData, FirebaseError, UpdateAgentVariables>): UseDataConnectMutationResult<UpdateAgentData, UpdateAgentVariables>;

export function useUpdateAgentConversation(options?: useDataConnectMutationOptions<UpdateAgentConversationData, FirebaseError, UpdateAgentConversationVariables>): UseDataConnectMutationResult<UpdateAgentConversationData, UpdateAgentConversationVariables>;
export function useUpdateAgentConversation(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateAgentConversationData, FirebaseError, UpdateAgentConversationVariables>): UseDataConnectMutationResult<UpdateAgentConversationData, UpdateAgentConversationVariables>;

export function useCreateDailyDispatch(options?: useDataConnectMutationOptions<CreateDailyDispatchData, FirebaseError, CreateDailyDispatchVariables>): UseDataConnectMutationResult<CreateDailyDispatchData, CreateDailyDispatchVariables>;
export function useCreateDailyDispatch(dc: DataConnect, options?: useDataConnectMutationOptions<CreateDailyDispatchData, FirebaseError, CreateDailyDispatchVariables>): UseDataConnectMutationResult<CreateDailyDispatchData, CreateDailyDispatchVariables>;

export function useUpdateDailyDispatch(options?: useDataConnectMutationOptions<UpdateDailyDispatchData, FirebaseError, UpdateDailyDispatchVariables>): UseDataConnectMutationResult<UpdateDailyDispatchData, UpdateDailyDispatchVariables>;
export function useUpdateDailyDispatch(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateDailyDispatchData, FirebaseError, UpdateDailyDispatchVariables>): UseDataConnectMutationResult<UpdateDailyDispatchData, UpdateDailyDispatchVariables>;

export function useDeleteDailyDispatch(options?: useDataConnectMutationOptions<DeleteDailyDispatchData, FirebaseError, DeleteDailyDispatchVariables>): UseDataConnectMutationResult<DeleteDailyDispatchData, DeleteDailyDispatchVariables>;
export function useDeleteDailyDispatch(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteDailyDispatchData, FirebaseError, DeleteDailyDispatchVariables>): UseDataConnectMutationResult<DeleteDailyDispatchData, DeleteDailyDispatchVariables>;

export function useCreatePayment(options?: useDataConnectMutationOptions<CreatePaymentData, FirebaseError, CreatePaymentVariables>): UseDataConnectMutationResult<CreatePaymentData, CreatePaymentVariables>;
export function useCreatePayment(dc: DataConnect, options?: useDataConnectMutationOptions<CreatePaymentData, FirebaseError, CreatePaymentVariables>): UseDataConnectMutationResult<CreatePaymentData, CreatePaymentVariables>;

export function useUpdatePayment(options?: useDataConnectMutationOptions<UpdatePaymentData, FirebaseError, UpdatePaymentVariables>): UseDataConnectMutationResult<UpdatePaymentData, UpdatePaymentVariables>;
export function useUpdatePayment(dc: DataConnect, options?: useDataConnectMutationOptions<UpdatePaymentData, FirebaseError, UpdatePaymentVariables>): UseDataConnectMutationResult<UpdatePaymentData, UpdatePaymentVariables>;

export function useDeletePayment(options?: useDataConnectMutationOptions<DeletePaymentData, FirebaseError, DeletePaymentVariables>): UseDataConnectMutationResult<DeletePaymentData, DeletePaymentVariables>;
export function useDeletePayment(dc: DataConnect, options?: useDataConnectMutationOptions<DeletePaymentData, FirebaseError, DeletePaymentVariables>): UseDataConnectMutationResult<DeletePaymentData, DeletePaymentVariables>;

export function useCreateTaxInvoice(options?: useDataConnectMutationOptions<CreateTaxInvoiceData, FirebaseError, CreateTaxInvoiceVariables>): UseDataConnectMutationResult<CreateTaxInvoiceData, CreateTaxInvoiceVariables>;
export function useCreateTaxInvoice(dc: DataConnect, options?: useDataConnectMutationOptions<CreateTaxInvoiceData, FirebaseError, CreateTaxInvoiceVariables>): UseDataConnectMutationResult<CreateTaxInvoiceData, CreateTaxInvoiceVariables>;

export function useUpdateTaxInvoice(options?: useDataConnectMutationOptions<UpdateTaxInvoiceData, FirebaseError, UpdateTaxInvoiceVariables>): UseDataConnectMutationResult<UpdateTaxInvoiceData, UpdateTaxInvoiceVariables>;
export function useUpdateTaxInvoice(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateTaxInvoiceData, FirebaseError, UpdateTaxInvoiceVariables>): UseDataConnectMutationResult<UpdateTaxInvoiceData, UpdateTaxInvoiceVariables>;

export function useDeleteTaxInvoice(options?: useDataConnectMutationOptions<DeleteTaxInvoiceData, FirebaseError, DeleteTaxInvoiceVariables>): UseDataConnectMutationResult<DeleteTaxInvoiceData, DeleteTaxInvoiceVariables>;
export function useDeleteTaxInvoice(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteTaxInvoiceData, FirebaseError, DeleteTaxInvoiceVariables>): UseDataConnectMutationResult<DeleteTaxInvoiceData, DeleteTaxInvoiceVariables>;

export function useCreateReceivable(options?: useDataConnectMutationOptions<CreateReceivableData, FirebaseError, CreateReceivableVariables>): UseDataConnectMutationResult<CreateReceivableData, CreateReceivableVariables>;
export function useCreateReceivable(dc: DataConnect, options?: useDataConnectMutationOptions<CreateReceivableData, FirebaseError, CreateReceivableVariables>): UseDataConnectMutationResult<CreateReceivableData, CreateReceivableVariables>;

export function useUpdateReceivable(options?: useDataConnectMutationOptions<UpdateReceivableData, FirebaseError, UpdateReceivableVariables>): UseDataConnectMutationResult<UpdateReceivableData, UpdateReceivableVariables>;
export function useUpdateReceivable(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateReceivableData, FirebaseError, UpdateReceivableVariables>): UseDataConnectMutationResult<UpdateReceivableData, UpdateReceivableVariables>;

export function useDeleteReceivable(options?: useDataConnectMutationOptions<DeleteReceivableData, FirebaseError, DeleteReceivableVariables>): UseDataConnectMutationResult<DeleteReceivableData, DeleteReceivableVariables>;
export function useDeleteReceivable(dc: DataConnect, options?: useDataConnectMutationOptions<DeleteReceivableData, FirebaseError, DeleteReceivableVariables>): UseDataConnectMutationResult<DeleteReceivableData, DeleteReceivableVariables>;

export function useListCompanies(options?: useDataConnectQueryOptions<ListCompaniesData>): UseDataConnectQueryResult<ListCompaniesData, undefined>;
export function useListCompanies(dc: DataConnect, options?: useDataConnectQueryOptions<ListCompaniesData>): UseDataConnectQueryResult<ListCompaniesData, undefined>;

export function useGetCompany(vars: GetCompanyVariables, options?: useDataConnectQueryOptions<GetCompanyData>): UseDataConnectQueryResult<GetCompanyData, GetCompanyVariables>;
export function useGetCompany(dc: DataConnect, vars: GetCompanyVariables, options?: useDataConnectQueryOptions<GetCompanyData>): UseDataConnectQueryResult<GetCompanyData, GetCompanyVariables>;

export function useListTeams(options?: useDataConnectQueryOptions<ListTeamsData>): UseDataConnectQueryResult<ListTeamsData, undefined>;
export function useListTeams(dc: DataConnect, options?: useDataConnectQueryOptions<ListTeamsData>): UseDataConnectQueryResult<ListTeamsData, undefined>;

export function useGetTeam(vars: GetTeamVariables, options?: useDataConnectQueryOptions<GetTeamData>): UseDataConnectQueryResult<GetTeamData, GetTeamVariables>;
export function useGetTeam(dc: DataConnect, vars: GetTeamVariables, options?: useDataConnectQueryOptions<GetTeamData>): UseDataConnectQueryResult<GetTeamData, GetTeamVariables>;

export function useListWorkers(options?: useDataConnectQueryOptions<ListWorkersData>): UseDataConnectQueryResult<ListWorkersData, undefined>;
export function useListWorkers(dc: DataConnect, options?: useDataConnectQueryOptions<ListWorkersData>): UseDataConnectQueryResult<ListWorkersData, undefined>;

export function useListPositions(options?: useDataConnectQueryOptions<ListPositionsData>): UseDataConnectQueryResult<ListPositionsData, undefined>;
export function useListPositions(dc: DataConnect, options?: useDataConnectQueryOptions<ListPositionsData>): UseDataConnectQueryResult<ListPositionsData, undefined>;

export function useGetWorker(vars: GetWorkerVariables, options?: useDataConnectQueryOptions<GetWorkerData>): UseDataConnectQueryResult<GetWorkerData, GetWorkerVariables>;
export function useGetWorker(dc: DataConnect, vars: GetWorkerVariables, options?: useDataConnectQueryOptions<GetWorkerData>): UseDataConnectQueryResult<GetWorkerData, GetWorkerVariables>;

export function useListSites(options?: useDataConnectQueryOptions<ListSitesData>): UseDataConnectQueryResult<ListSitesData, undefined>;
export function useListSites(dc: DataConnect, options?: useDataConnectQueryOptions<ListSitesData>): UseDataConnectQueryResult<ListSitesData, undefined>;

export function useGetSite(vars: GetSiteVariables, options?: useDataConnectQueryOptions<GetSiteData>): UseDataConnectQueryResult<GetSiteData, GetSiteVariables>;
export function useGetSite(dc: DataConnect, vars: GetSiteVariables, options?: useDataConnectQueryOptions<GetSiteData>): UseDataConnectQueryResult<GetSiteData, GetSiteVariables>;

export function useListDailyReports(options?: useDataConnectQueryOptions<ListDailyReportsData>): UseDataConnectQueryResult<ListDailyReportsData, undefined>;
export function useListDailyReports(dc: DataConnect, options?: useDataConnectQueryOptions<ListDailyReportsData>): UseDataConnectQueryResult<ListDailyReportsData, undefined>;

export function useListDailyReportWorkers(options?: useDataConnectQueryOptions<ListDailyReportWorkersData>): UseDataConnectQueryResult<ListDailyReportWorkersData, undefined>;
export function useListDailyReportWorkers(dc: DataConnect, options?: useDataConnectQueryOptions<ListDailyReportWorkersData>): UseDataConnectQueryResult<ListDailyReportWorkersData, undefined>;

export function useListAppUsers(options?: useDataConnectQueryOptions<ListAppUsersData>): UseDataConnectQueryResult<ListAppUsersData, undefined>;
export function useListAppUsers(dc: DataConnect, options?: useDataConnectQueryOptions<ListAppUsersData>): UseDataConnectQueryResult<ListAppUsersData, undefined>;

export function useListMenuConfigs(options?: useDataConnectQueryOptions<ListMenuConfigsData>): UseDataConnectQueryResult<ListMenuConfigsData, undefined>;
export function useListMenuConfigs(dc: DataConnect, options?: useDataConnectQueryOptions<ListMenuConfigsData>): UseDataConnectQueryResult<ListMenuConfigsData, undefined>;

export function useListSystemLogs(options?: useDataConnectQueryOptions<ListSystemLogsData>): UseDataConnectQueryResult<ListSystemLogsData, undefined>;
export function useListSystemLogs(dc: DataConnect, options?: useDataConnectQueryOptions<ListSystemLogsData>): UseDataConnectQueryResult<ListSystemLogsData, undefined>;

export function useListAuditLogs(options?: useDataConnectQueryOptions<ListAuditLogsData>): UseDataConnectQueryResult<ListAuditLogsData, undefined>;
export function useListAuditLogs(dc: DataConnect, options?: useDataConnectQueryOptions<ListAuditLogsData>): UseDataConnectQueryResult<ListAuditLogsData, undefined>;

export function useListAgents(options?: useDataConnectQueryOptions<ListAgentsData>): UseDataConnectQueryResult<ListAgentsData, undefined>;
export function useListAgents(dc: DataConnect, options?: useDataConnectQueryOptions<ListAgentsData>): UseDataConnectQueryResult<ListAgentsData, undefined>;

export function useListAgentConversations(options?: useDataConnectQueryOptions<ListAgentConversationsData>): UseDataConnectQueryResult<ListAgentConversationsData, undefined>;
export function useListAgentConversations(dc: DataConnect, options?: useDataConnectQueryOptions<ListAgentConversationsData>): UseDataConnectQueryResult<ListAgentConversationsData, undefined>;

export function useListSettings(options?: useDataConnectQueryOptions<ListSettingsData>): UseDataConnectQueryResult<ListSettingsData, undefined>;
export function useListSettings(dc: DataConnect, options?: useDataConnectQueryOptions<ListSettingsData>): UseDataConnectQueryResult<ListSettingsData, undefined>;

export function useListSystemConfigs(options?: useDataConnectQueryOptions<ListSystemConfigsData>): UseDataConnectQueryResult<ListSystemConfigsData, undefined>;
export function useListSystemConfigs(dc: DataConnect, options?: useDataConnectQueryOptions<ListSystemConfigsData>): UseDataConnectQueryResult<ListSystemConfigsData, undefined>;

export function useListAllCompanies(vars?: ListAllCompaniesVariables, options?: useDataConnectQueryOptions<ListAllCompaniesData>): UseDataConnectQueryResult<ListAllCompaniesData, ListAllCompaniesVariables>;
export function useListAllCompanies(dc: DataConnect, vars?: ListAllCompaniesVariables, options?: useDataConnectQueryOptions<ListAllCompaniesData>): UseDataConnectQueryResult<ListAllCompaniesData, ListAllCompaniesVariables>;

export function useListAllTeams(vars?: ListAllTeamsVariables, options?: useDataConnectQueryOptions<ListAllTeamsData>): UseDataConnectQueryResult<ListAllTeamsData, ListAllTeamsVariables>;
export function useListAllTeams(dc: DataConnect, vars?: ListAllTeamsVariables, options?: useDataConnectQueryOptions<ListAllTeamsData>): UseDataConnectQueryResult<ListAllTeamsData, ListAllTeamsVariables>;

export function useListAllWorkers(vars?: ListAllWorkersVariables, options?: useDataConnectQueryOptions<ListAllWorkersData>): UseDataConnectQueryResult<ListAllWorkersData, ListAllWorkersVariables>;
export function useListAllWorkers(dc: DataConnect, vars?: ListAllWorkersVariables, options?: useDataConnectQueryOptions<ListAllWorkersData>): UseDataConnectQueryResult<ListAllWorkersData, ListAllWorkersVariables>;

export function useListAllPositions(vars?: ListAllPositionsVariables, options?: useDataConnectQueryOptions<ListAllPositionsData>): UseDataConnectQueryResult<ListAllPositionsData, ListAllPositionsVariables>;
export function useListAllPositions(dc: DataConnect, vars?: ListAllPositionsVariables, options?: useDataConnectQueryOptions<ListAllPositionsData>): UseDataConnectQueryResult<ListAllPositionsData, ListAllPositionsVariables>;

export function useListAllSites(vars?: ListAllSitesVariables, options?: useDataConnectQueryOptions<ListAllSitesData>): UseDataConnectQueryResult<ListAllSitesData, ListAllSitesVariables>;
export function useListAllSites(dc: DataConnect, vars?: ListAllSitesVariables, options?: useDataConnectQueryOptions<ListAllSitesData>): UseDataConnectQueryResult<ListAllSitesData, ListAllSitesVariables>;

export function useListAllDailyReports(vars?: ListAllDailyReportsVariables, options?: useDataConnectQueryOptions<ListAllDailyReportsData>): UseDataConnectQueryResult<ListAllDailyReportsData, ListAllDailyReportsVariables>;
export function useListAllDailyReports(dc: DataConnect, vars?: ListAllDailyReportsVariables, options?: useDataConnectQueryOptions<ListAllDailyReportsData>): UseDataConnectQueryResult<ListAllDailyReportsData, ListAllDailyReportsVariables>;

export function useListAllDailyReportWorkers(vars?: ListAllDailyReportWorkersVariables, options?: useDataConnectQueryOptions<ListAllDailyReportWorkersData>): UseDataConnectQueryResult<ListAllDailyReportWorkersData, ListAllDailyReportWorkersVariables>;
export function useListAllDailyReportWorkers(dc: DataConnect, vars?: ListAllDailyReportWorkersVariables, options?: useDataConnectQueryOptions<ListAllDailyReportWorkersData>): UseDataConnectQueryResult<ListAllDailyReportWorkersData, ListAllDailyReportWorkersVariables>;

export function useListAllAppUsers(vars?: ListAllAppUsersVariables, options?: useDataConnectQueryOptions<ListAllAppUsersData>): UseDataConnectQueryResult<ListAllAppUsersData, ListAllAppUsersVariables>;
export function useListAllAppUsers(dc: DataConnect, vars?: ListAllAppUsersVariables, options?: useDataConnectQueryOptions<ListAllAppUsersData>): UseDataConnectQueryResult<ListAllAppUsersData, ListAllAppUsersVariables>;

export function useListAllMenuConfigs(vars?: ListAllMenuConfigsVariables, options?: useDataConnectQueryOptions<ListAllMenuConfigsData>): UseDataConnectQueryResult<ListAllMenuConfigsData, ListAllMenuConfigsVariables>;
export function useListAllMenuConfigs(dc: DataConnect, vars?: ListAllMenuConfigsVariables, options?: useDataConnectQueryOptions<ListAllMenuConfigsData>): UseDataConnectQueryResult<ListAllMenuConfigsData, ListAllMenuConfigsVariables>;

export function useListAllSystemLogs(vars?: ListAllSystemLogsVariables, options?: useDataConnectQueryOptions<ListAllSystemLogsData>): UseDataConnectQueryResult<ListAllSystemLogsData, ListAllSystemLogsVariables>;
export function useListAllSystemLogs(dc: DataConnect, vars?: ListAllSystemLogsVariables, options?: useDataConnectQueryOptions<ListAllSystemLogsData>): UseDataConnectQueryResult<ListAllSystemLogsData, ListAllSystemLogsVariables>;

export function useListAllAuditLogs(vars?: ListAllAuditLogsVariables, options?: useDataConnectQueryOptions<ListAllAuditLogsData>): UseDataConnectQueryResult<ListAllAuditLogsData, ListAllAuditLogsVariables>;
export function useListAllAuditLogs(dc: DataConnect, vars?: ListAllAuditLogsVariables, options?: useDataConnectQueryOptions<ListAllAuditLogsData>): UseDataConnectQueryResult<ListAllAuditLogsData, ListAllAuditLogsVariables>;

export function useListAllAgents(vars?: ListAllAgentsVariables, options?: useDataConnectQueryOptions<ListAllAgentsData>): UseDataConnectQueryResult<ListAllAgentsData, ListAllAgentsVariables>;
export function useListAllAgents(dc: DataConnect, vars?: ListAllAgentsVariables, options?: useDataConnectQueryOptions<ListAllAgentsData>): UseDataConnectQueryResult<ListAllAgentsData, ListAllAgentsVariables>;

export function useListAllAgentConversations(vars?: ListAllAgentConversationsVariables, options?: useDataConnectQueryOptions<ListAllAgentConversationsData>): UseDataConnectQueryResult<ListAllAgentConversationsData, ListAllAgentConversationsVariables>;
export function useListAllAgentConversations(dc: DataConnect, vars?: ListAllAgentConversationsVariables, options?: useDataConnectQueryOptions<ListAllAgentConversationsData>): UseDataConnectQueryResult<ListAllAgentConversationsData, ListAllAgentConversationsVariables>;

export function useListAllSettings(vars?: ListAllSettingsVariables, options?: useDataConnectQueryOptions<ListAllSettingsData>): UseDataConnectQueryResult<ListAllSettingsData, ListAllSettingsVariables>;
export function useListAllSettings(dc: DataConnect, vars?: ListAllSettingsVariables, options?: useDataConnectQueryOptions<ListAllSettingsData>): UseDataConnectQueryResult<ListAllSettingsData, ListAllSettingsVariables>;

export function useListAllSystemConfigs(vars?: ListAllSystemConfigsVariables, options?: useDataConnectQueryOptions<ListAllSystemConfigsData>): UseDataConnectQueryResult<ListAllSystemConfigsData, ListAllSystemConfigsVariables>;
export function useListAllSystemConfigs(dc: DataConnect, vars?: ListAllSystemConfigsVariables, options?: useDataConnectQueryOptions<ListAllSystemConfigsData>): UseDataConnectQueryResult<ListAllSystemConfigsData, ListAllSystemConfigsVariables>;

export function useListAllAccommodations(vars?: ListAllAccommodationsVariables, options?: useDataConnectQueryOptions<ListAllAccommodationsData>): UseDataConnectQueryResult<ListAllAccommodationsData, ListAllAccommodationsVariables>;
export function useListAllAccommodations(dc: DataConnect, vars?: ListAllAccommodationsVariables, options?: useDataConnectQueryOptions<ListAllAccommodationsData>): UseDataConnectQueryResult<ListAllAccommodationsData, ListAllAccommodationsVariables>;

export function useListAllAccommodationAssignments(vars?: ListAllAccommodationAssignmentsVariables, options?: useDataConnectQueryOptions<ListAllAccommodationAssignmentsData>): UseDataConnectQueryResult<ListAllAccommodationAssignmentsData, ListAllAccommodationAssignmentsVariables>;
export function useListAllAccommodationAssignments(dc: DataConnect, vars?: ListAllAccommodationAssignmentsVariables, options?: useDataConnectQueryOptions<ListAllAccommodationAssignmentsData>): UseDataConnectQueryResult<ListAllAccommodationAssignmentsData, ListAllAccommodationAssignmentsVariables>;

export function useListAllUtilityRecords(vars?: ListAllUtilityRecordsVariables, options?: useDataConnectQueryOptions<ListAllUtilityRecordsData>): UseDataConnectQueryResult<ListAllUtilityRecordsData, ListAllUtilityRecordsVariables>;
export function useListAllUtilityRecords(dc: DataConnect, vars?: ListAllUtilityRecordsVariables, options?: useDataConnectQueryOptions<ListAllUtilityRecordsData>): UseDataConnectQueryResult<ListAllUtilityRecordsData, ListAllUtilityRecordsVariables>;

export function useListAllAccommodationBillingDocuments(vars?: ListAllAccommodationBillingDocumentsVariables, options?: useDataConnectQueryOptions<ListAllAccommodationBillingDocumentsData>): UseDataConnectQueryResult<ListAllAccommodationBillingDocumentsData, ListAllAccommodationBillingDocumentsVariables>;
export function useListAllAccommodationBillingDocuments(dc: DataConnect, vars?: ListAllAccommodationBillingDocumentsVariables, options?: useDataConnectQueryOptions<ListAllAccommodationBillingDocumentsData>): UseDataConnectQueryResult<ListAllAccommodationBillingDocumentsData, ListAllAccommodationBillingDocumentsVariables>;

export function useListAllAccommodationBillingLineItems(vars?: ListAllAccommodationBillingLineItemsVariables, options?: useDataConnectQueryOptions<ListAllAccommodationBillingLineItemsData>): UseDataConnectQueryResult<ListAllAccommodationBillingLineItemsData, ListAllAccommodationBillingLineItemsVariables>;
export function useListAllAccommodationBillingLineItems(dc: DataConnect, vars?: ListAllAccommodationBillingLineItemsVariables, options?: useDataConnectQueryOptions<ListAllAccommodationBillingLineItemsData>): UseDataConnectQueryResult<ListAllAccommodationBillingLineItemsData, ListAllAccommodationBillingLineItemsVariables>;

export function useListAllAdvancePayments(vars?: ListAllAdvancePaymentsVariables, options?: useDataConnectQueryOptions<ListAllAdvancePaymentsData>): UseDataConnectQueryResult<ListAllAdvancePaymentsData, ListAllAdvancePaymentsVariables>;
export function useListAllAdvancePayments(dc: DataConnect, vars?: ListAllAdvancePaymentsVariables, options?: useDataConnectQueryOptions<ListAllAdvancePaymentsData>): UseDataConnectQueryResult<ListAllAdvancePaymentsData, ListAllAdvancePaymentsVariables>;

export function useListAllSmartMemoCategories(vars?: ListAllSmartMemoCategoriesVariables, options?: useDataConnectQueryOptions<ListAllSmartMemoCategoriesData>): UseDataConnectQueryResult<ListAllSmartMemoCategoriesData, ListAllSmartMemoCategoriesVariables>;
export function useListAllSmartMemoCategories(dc: DataConnect, vars?: ListAllSmartMemoCategoriesVariables, options?: useDataConnectQueryOptions<ListAllSmartMemoCategoriesData>): UseDataConnectQueryResult<ListAllSmartMemoCategoriesData, ListAllSmartMemoCategoriesVariables>;

export function useListAllSmartMemos(vars?: ListAllSmartMemosVariables, options?: useDataConnectQueryOptions<ListAllSmartMemosData>): UseDataConnectQueryResult<ListAllSmartMemosData, ListAllSmartMemosVariables>;
export function useListAllSmartMemos(dc: DataConnect, vars?: ListAllSmartMemosVariables, options?: useDataConnectQueryOptions<ListAllSmartMemosData>): UseDataConnectQueryResult<ListAllSmartMemosData, ListAllSmartMemosVariables>;

export function useListAllVehicles(vars?: ListAllVehiclesVariables, options?: useDataConnectQueryOptions<ListAllVehiclesData>): UseDataConnectQueryResult<ListAllVehiclesData, ListAllVehiclesVariables>;
export function useListAllVehicles(dc: DataConnect, vars?: ListAllVehiclesVariables, options?: useDataConnectQueryOptions<ListAllVehiclesData>): UseDataConnectQueryResult<ListAllVehiclesData, ListAllVehiclesVariables>;

export function useListAllVehicleAssignments(vars?: ListAllVehicleAssignmentsVariables, options?: useDataConnectQueryOptions<ListAllVehicleAssignmentsData>): UseDataConnectQueryResult<ListAllVehicleAssignmentsData, ListAllVehicleAssignmentsVariables>;
export function useListAllVehicleAssignments(dc: DataConnect, vars?: ListAllVehicleAssignmentsVariables, options?: useDataConnectQueryOptions<ListAllVehicleAssignmentsData>): UseDataConnectQueryResult<ListAllVehicleAssignmentsData, ListAllVehicleAssignmentsVariables>;

export function useListAllVehicleExpenses(vars?: ListAllVehicleExpensesVariables, options?: useDataConnectQueryOptions<ListAllVehicleExpensesData>): UseDataConnectQueryResult<ListAllVehicleExpensesData, ListAllVehicleExpensesVariables>;
export function useListAllVehicleExpenses(dc: DataConnect, vars?: ListAllVehicleExpensesVariables, options?: useDataConnectQueryOptions<ListAllVehicleExpensesData>): UseDataConnectQueryResult<ListAllVehicleExpensesData, ListAllVehicleExpensesVariables>;

export function useListAllVehicleBillingDocuments(vars?: ListAllVehicleBillingDocumentsVariables, options?: useDataConnectQueryOptions<ListAllVehicleBillingDocumentsData>): UseDataConnectQueryResult<ListAllVehicleBillingDocumentsData, ListAllVehicleBillingDocumentsVariables>;
export function useListAllVehicleBillingDocuments(dc: DataConnect, vars?: ListAllVehicleBillingDocumentsVariables, options?: useDataConnectQueryOptions<ListAllVehicleBillingDocumentsData>): UseDataConnectQueryResult<ListAllVehicleBillingDocumentsData, ListAllVehicleBillingDocumentsVariables>;

export function useListAllDailyDispatches(vars?: ListAllDailyDispatchesVariables, options?: useDataConnectQueryOptions<ListAllDailyDispatchesData>): UseDataConnectQueryResult<ListAllDailyDispatchesData, ListAllDailyDispatchesVariables>;
export function useListAllDailyDispatches(dc: DataConnect, vars?: ListAllDailyDispatchesVariables, options?: useDataConnectQueryOptions<ListAllDailyDispatchesData>): UseDataConnectQueryResult<ListAllDailyDispatchesData, ListAllDailyDispatchesVariables>;

export function useListAllPayments(vars?: ListAllPaymentsVariables, options?: useDataConnectQueryOptions<ListAllPaymentsData>): UseDataConnectQueryResult<ListAllPaymentsData, ListAllPaymentsVariables>;
export function useListAllPayments(dc: DataConnect, vars?: ListAllPaymentsVariables, options?: useDataConnectQueryOptions<ListAllPaymentsData>): UseDataConnectQueryResult<ListAllPaymentsData, ListAllPaymentsVariables>;

export function useListAllTaxInvoices(vars?: ListAllTaxInvoicesVariables, options?: useDataConnectQueryOptions<ListAllTaxInvoicesData>): UseDataConnectQueryResult<ListAllTaxInvoicesData, ListAllTaxInvoicesVariables>;
export function useListAllTaxInvoices(dc: DataConnect, vars?: ListAllTaxInvoicesVariables, options?: useDataConnectQueryOptions<ListAllTaxInvoicesData>): UseDataConnectQueryResult<ListAllTaxInvoicesData, ListAllTaxInvoicesVariables>;

export function useListAllReceivables(vars?: ListAllReceivablesVariables, options?: useDataConnectQueryOptions<ListAllReceivablesData>): UseDataConnectQueryResult<ListAllReceivablesData, ListAllReceivablesVariables>;
export function useListAllReceivables(dc: DataConnect, vars?: ListAllReceivablesVariables, options?: useDataConnectQueryOptions<ListAllReceivablesData>): UseDataConnectQueryResult<ListAllReceivablesData, ListAllReceivablesVariables>;
