export type SystemCollectionSource = 'firestore';

export interface SystemCollectionConfig {
    id: string;
    label: string;
    description: string;
    source: SystemCollectionSource;
}

export const SYSTEM_COLLECTIONS: SystemCollectionConfig[] = [
    { id: 'companies', label: '회사 (Companies)', description: '인력 업체 및 소속 회사 정보', source: 'firestore' },
    { id: 'teams', label: '팀 (Teams)', description: '작업 팀 및 반장 정보', source: 'firestore' },
    { id: 'workers', label: '작업자 (Workers)', description: '등록된 건설 작업자 목록', source: 'firestore' },
    { id: 'office_staff', label: '사무실 직원 (Office Staff)', description: '사무실 직원 개인정보, 급여, 계좌, 계정 연동 정보', source: 'firestore' },
    { id: 'app_users', label: '앱 사용자 (App Users)', description: '시스템 접속 계정', source: 'firestore' },
    { id: 'login_logs', label: '로그인 로그 (Login Logs)', description: '로그인 성공/실패 및 로그아웃 접속 이력', source: 'firestore' },
    { id: 'sites', label: '현장 (Sites)', description: '공사 현장 및 배정 정보', source: 'firestore' },
    { id: 'daily_dispatches', label: '일일 배차 (Dispatches)', description: '일일 작업자 배차 정보', source: 'firestore' },
    { id: 'field_schedule_requests', label: '현장 일정 요청', description: '현장별 사전 요청 인원과 휴무자 정보', source: 'firestore' },
    { id: 'schedule_confirmation_boards', label: '일정확정보드', description: '현장별 확정 작업자/지원팀 입력 보드', source: 'firestore' },
    { id: 'daily_reports', label: '작업일보 (Daily Reports)', description: '매일 작성된 출력/공수 일보', source: 'firestore' },
    { id: 'daily_report_workers', label: '일보 상세 (Report Workers)', description: '작업일보별 작업자 공수 상세', source: 'firestore' },
    { id: 'daily_report_logs', label: '출력일보 로그 (Daily Report Logs)', description: '출력일보 저장/수정/삭제 변경 이력', source: 'firestore' },
    { id: 'recruiting_referrers', label: '소개자 (Recruiting Referrers)', description: '소개소/작업자/사무실 직원 등 소개비 지급 대상자', source: 'firestore' },
    { id: 'service_worker_referrals', label: '용역 소개 연결 (Service Referrals)', description: '용역팀 작업자와 소개자의 연결 및 요율 정보', source: 'firestore' },
    { id: 'service_referral_daily_lines', label: '소개소 일별 정산 (Referral Daily Lines)', description: '출력일보 기반 일별 소개비 및 수수료 정산 라인', source: 'firestore' },
    { id: 'service_referral_monthly_settlements', label: '소개소 월별 정산 (Referral Settlements)', description: '소개자별 월별 정산 문서', source: 'firestore' },
    { id: 'service_referral_settings', label: '소개소 수익모델 (Referral Settings)', description: '소개비/일일수수료 기본 수익모델 설정', source: 'firestore' },
    { id: 'service_worker_history', label: '작업자 이력 (Service Worker History)', description: '소개소 작업자 상태, 소개자, 현장, 정산, 지급 이벤트 이력', source: 'firestore' },
    { id: 'service_referral_payments', label: '소개소 지급관리 (Referral Payments)', description: '소개자별 정산 지급 승인, 지급 완료, 취소 이력', source: 'firestore' },
    { id: 'service_referral_deposits', label: '소개소 입금관리 (Referral Deposits)', description: '소개비 수입 예정액, 실제 입금, 증빙, 차액 관리', source: 'firestore' },
    { id: 'service_referral_receivables', label: '소개소 미수금 (Referral Receivables)', description: '입금 차액 기반 미수금, 연체, 회수 상태 관리', source: 'firestore' },
    { id: 'database_logs', label: '통합 DB 로그 (Database Logs)', description: '작업자/팀/현장/회사/계좌 저장·수정·삭제 변경 이력', source: 'firestore' },
    { id: 'tax_invoices', label: '세금계산서 (Invoices)', description: '매입/매출 세금계산서', source: 'firestore' },
    { id: 'payments', label: '입출금 (Payments)', description: '통장 입출금 내역', source: 'firestore' },
    { id: 'receivables', label: '미수금 (Receivables)', description: '미수금 추적 관리', source: 'firestore' },
    { id: 'advance_payments', label: '가불 공제 (Advance Pay)', description: '작업자 가불 및 공제 내역', source: 'firestore' },
    { id: 'vehicles', label: '차량 (Vehicles)', description: '보유 차량 관리', source: 'firestore' },
    { id: 'vehicle_assignments', label: '차량 배정 (V-Assign)', description: '차량 운행 및 배정 기록', source: 'firestore' },
    { id: 'vehicle_expenses', label: '차량 지출 (V-Expense)', description: '주유비 및 수리비 등 차량 지출', source: 'firestore' },
    { id: 'vehicle_billing_documents', label: '차량 청구서 (V-Bills)', description: '월별 차량 비용 청구 문서', source: 'firestore' },
    { id: 'vehicle_billing_logs', label: '차량 청구 로그 (V-Bill Logs)', description: '차량 청구서 저장·수정·삭제 변경 이력', source: 'firestore' },
    { id: 'card_billing_logs', label: '카드 청구 로그 (Card Bill Logs)', description: '카드 청구서 저장·수정·삭제 변경 이력', source: 'firestore' },
    { id: 'support_cancellation_logs', label: '지원 처리내역 (Support Close Logs)', description: '차량/카드/숙소 사용취소·만료·정지 처리 이력', source: 'firestore' },
    { id: 'material_logs', label: '자재관리 로그 (Material Logs)', description: '자재 마스터/입고/출고 저장·수정·삭제 변경 이력', source: 'firestore' },
    { id: 'workbook_ledger_logs', label: '매입매출 장부 로그 (Workbook Ledger Logs)', description: '매입매출 장부 등록·수정·삭제 변경 이력', source: 'firestore' },
    { id: 'accommodations', label: '숙소 (Accommodations)', description: '작업자 숙소 정보', source: 'firestore' },
    { id: 'utility_records', label: '공과금 (Utilities)', description: '숙소 공과금 및 관리비 내역', source: 'firestore' },
    { id: 'accommodation_assignments', label: '숙소 배정 (A-Assign)', description: '숙소 입퇴실 기록', source: 'firestore' },
    { id: 'accommodation_billing_logs', label: '숙소 청구 로그 (Accommodation Bill Logs)', description: '숙소 청구서 저장·수정·삭제 변경 이력', source: 'firestore' },
    { id: 'accommodation_billing_documents', label: '숙소 청구서 (A-Bills)', description: '월별 숙소비 청구 문서', source: 'firestore' },
    { id: 'accommodation_billing_line_items', label: '숙소 청구 항목 (A-Lines)', description: '숙소 청구서 상세 항목', source: 'firestore' },
    { id: 'positions', label: '직책 (Positions)', description: '직책 및 시스템 권한 설정', source: 'firestore' },
    { id: 'menus', label: '메뉴 (Menus)', description: '사이드바 메뉴 구조 및 설정', source: 'firestore' },
    { id: 'menu_configs', label: '메뉴 설정 (Menu Configs)', description: '동적 메뉴 설정 데이터', source: 'firestore' },
    { id: 'settings', label: '환경 설정 (Settings)', description: '전역 시스템 설정', source: 'firestore' },
    { id: 'system_configs', label: '시스템 구성 (Sys Configs)', description: '시스템 내부 구성 데이터', source: 'firestore' },
    { id: 'smart_memos', label: '스마트 메모 (Memos)', description: '사용자 메모 데이터', source: 'firestore' },
    { id: 'smart_memo_categories', label: '메모 카테고리 (Memo Cats)', description: '메모 카테고리 분류', source: 'firestore' },
    { id: 'agents', label: 'AI 에이전트 (Agents)', description: '등록된 AI 에이전트 정보', source: 'firestore' },
    { id: 'agent_conversations', label: '대화 기록 (Conversations)', description: 'AI 에이전트 대화 기록', source: 'firestore' },
    { id: 'system_logs', label: '시스템 로그 (Sys Logs)', description: '시스템 오류 및 트래픽 로그', source: 'firestore' },
    { id: 'audit_logs', label: '감사 로그 (Audit Logs)', description: '사용자 주요 행동 이력', source: 'firestore' },
];
