extend type AccommodationAssignment {
  """
  ✨ Implicit foreign key field based on `AccommodationAssignment`.`accommodation`. It must match the value of `Accommodation`.`id`. See `@ref` for how to customize it.
  """
  accommodationId: UUID! @fdc_generated(from: "AccommodationAssignment.accommodation", purpose: IMPLICIT_REF_FIELD)
}
extend type AccommodationBillingDocument {
  """
  ✨ Implicit foreign key field based on `AccommodationBillingDocument`.`issuedToWorker`. It must match the value of `Worker`.`id`. See `@ref` for how to customize it.
  """
  issuedToWorkerId: UUID @fdc_generated(from: "AccommodationBillingDocument.issuedToWorker", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `AccommodationBillingDocument`.`team`. It must match the value of `Team`.`id`. See `@ref` for how to customize it.
  """
  teamId: UUID @fdc_generated(from: "AccommodationBillingDocument.team", purpose: IMPLICIT_REF_FIELD)
}
extend type AccommodationBillingLineItem {
  """
  ✨ Implicit foreign key field based on `AccommodationBillingLineItem`.`billingDocument`. It must match the value of `AccommodationBillingDocument`.`id`. See `@ref` for how to customize it.
  """
  billingDocumentId: UUID! @fdc_generated(from: "AccommodationBillingLineItem.billingDocument", purpose: IMPLICIT_REF_FIELD)
}
extend type AdvancePayment {
  """
  ✨ Implicit foreign key field based on `AdvancePayment`.`team`. It must match the value of `Team`.`id`. See `@ref` for how to customize it.
  """
  teamId: UUID @fdc_generated(from: "AdvancePayment.team", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `AdvancePayment`.`worker`. It must match the value of `Worker`.`id`. See `@ref` for how to customize it.
  """
  workerId: UUID @fdc_generated(from: "AdvancePayment.worker", purpose: IMPLICIT_REF_FIELD)
}
extend type DailyReport {
  """
  ✨ Implicit foreign key field based on `DailyReport`.`site`. It must match the value of `Site`.`id`. See `@ref` for how to customize it.
  """
  siteId: UUID @fdc_generated(from: "DailyReport.site", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `DailyReport`.`team`. It must match the value of `Team`.`id`. See `@ref` for how to customize it.
  """
  teamId: UUID! @fdc_generated(from: "DailyReport.team", purpose: IMPLICIT_REF_FIELD)
}
extend type DailyReportWorker {
  """
  ✨ Implicit foreign key field based on `DailyReportWorker`.`dailyReport`. It must match the value of `DailyReport`.`id`. See `@ref` for how to customize it.
  """
  dailyReportId: UUID! @fdc_generated(from: "DailyReportWorker.dailyReport", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `DailyReportWorker`.`worker`. It must match the value of `Worker`.`id`. See `@ref` for how to customize it.
  """
  workerId: UUID! @fdc_generated(from: "DailyReportWorker.worker", purpose: IMPLICIT_REF_FIELD)
}
extend type SmartMemo {
  """
  ✨ Implicit foreign key field based on `SmartMemo`.`category`. It must match the value of `SmartMemoCategory`.`id`. See `@ref` for how to customize it.
  """
  categoryId: UUID @fdc_generated(from: "SmartMemo.category", purpose: IMPLICIT_REF_FIELD)
}
extend type Team {
  """
  ✨ Implicit foreign key field based on `Team`.`company`. It must match the value of `Company`.`id`. See `@ref` for how to customize it.
  """
  companyId: UUID @fdc_generated(from: "Team.company", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Team`.`leader`. It must match the value of `Worker`.`id`. See `@ref` for how to customize it.
  """
  leaderId: UUID @fdc_generated(from: "Team.leader", purpose: IMPLICIT_REF_FIELD)
}
extend type UtilityRecord {
  """
  ✨ Implicit foreign key field based on `UtilityRecord`.`accommodation`. It must match the value of `Accommodation`.`id`. See `@ref` for how to customize it.
  """
  accommodationId: UUID! @fdc_generated(from: "UtilityRecord.accommodation", purpose: IMPLICIT_REF_FIELD)
}
extend type VehicleAssignment {
  """
  ✨ Implicit foreign key field based on `VehicleAssignment`.`vehicle`. It must match the value of `Vehicle`.`id`. See `@ref` for how to customize it.
  """
  vehicleId: UUID! @fdc_generated(from: "VehicleAssignment.vehicle", purpose: IMPLICIT_REF_FIELD)
}
extend type VehicleExpense {
  """
  ✨ Implicit foreign key field based on `VehicleExpense`.`vehicle`. It must match the value of `Vehicle`.`id`. See `@ref` for how to customize it.
  """
  vehicleId: UUID! @fdc_generated(from: "VehicleExpense.vehicle", purpose: IMPLICIT_REF_FIELD)
}
extend type Worker {
  """
  ✨ Implicit foreign key field based on `Worker`.`team`. It must match the value of `Team`.`id`. See `@ref` for how to customize it.
  """
  teamId: UUID @fdc_generated(from: "Worker.team", purpose: IMPLICIT_REF_FIELD)
}
