extend type Query {
  """
  ✨ Look up a single `Accommodation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  accommodation(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Accommodation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Accommodation_FirstRow
  ): Accommodation @fdc_generated(from: "Accommodation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `AccommodationAssignment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  accommodationAssignment(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AccommodationAssignment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AccommodationAssignment_FirstRow
  ): AccommodationAssignment @fdc_generated(from: "AccommodationAssignment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `AccommodationBillingDocument` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  accommodationBillingDocument(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AccommodationBillingDocument_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AccommodationBillingDocument_FirstRow
  ): AccommodationBillingDocument @fdc_generated(from: "AccommodationBillingDocument", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `AccommodationBillingLineItem` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  accommodationBillingLineItem(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AccommodationBillingLineItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AccommodationBillingLineItem_FirstRow
  ): AccommodationBillingLineItem @fdc_generated(from: "AccommodationBillingLineItem", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `AdvancePayment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  advancePayment(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: AdvancePayment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AdvancePayment_FirstRow
  ): AdvancePayment @fdc_generated(from: "AdvancePayment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Agent` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  agent(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Agent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Agent_FirstRow
  ): Agent @fdc_generated(from: "Agent", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `AgentConversation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  agentConversation(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: AgentConversation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AgentConversation_FirstRow
  ): AgentConversation @fdc_generated(from: "AgentConversation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `AppUser` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  appUser(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: AppUser_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AppUser_FirstRow
  ): AppUser @fdc_generated(from: "AppUser", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `AuditLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  auditLog(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: AuditLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AuditLog_FirstRow
  ): AuditLog @fdc_generated(from: "AuditLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Company` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  company(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Company_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Company_FirstRow
  ): Company @fdc_generated(from: "Company", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DailyDispatch` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  dailyDispatch(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DailyDispatch_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DailyDispatch_FirstRow
  ): DailyDispatch @fdc_generated(from: "DailyDispatch", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DailyReport` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  dailyReport(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DailyReport_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DailyReport_FirstRow
  ): DailyReport @fdc_generated(from: "DailyReport", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DailyReportWorker` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  dailyReportWorker(
    """
    The key used to identify the object.
    """
    key: DailyReportWorker_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DailyReportWorker_FirstRow
  ): DailyReportWorker @fdc_generated(from: "DailyReportWorker", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `MenuConfig` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  menuConfig(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: MenuConfig_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MenuConfig_FirstRow
  ): MenuConfig @fdc_generated(from: "MenuConfig", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Payment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  payment(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Payment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Payment_FirstRow
  ): Payment @fdc_generated(from: "Payment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Position` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  position(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Position_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Position_FirstRow
  ): Position @fdc_generated(from: "Position", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Receivable` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  receivable(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Receivable_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Receivable_FirstRow
  ): Receivable @fdc_generated(from: "Receivable", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Setting` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  setting(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Setting_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Setting_FirstRow
  ): Setting @fdc_generated(from: "Setting", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Site` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  site(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Site_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Site_FirstRow
  ): Site @fdc_generated(from: "Site", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SmartMemo` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  smartMemo(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SmartMemo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SmartMemo_FirstRow
  ): SmartMemo @fdc_generated(from: "SmartMemo", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SmartMemoCategory` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  smartMemoCategory(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SmartMemoCategory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SmartMemoCategory_FirstRow
  ): SmartMemoCategory @fdc_generated(from: "SmartMemoCategory", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SystemConfig` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  systemConfig(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: SystemConfig_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SystemConfig_FirstRow
  ): SystemConfig @fdc_generated(from: "SystemConfig", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SystemLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  systemLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SystemLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SystemLog_FirstRow
  ): SystemLog @fdc_generated(from: "SystemLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TaxInvoice` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  taxInvoice(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TaxInvoice_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TaxInvoice_FirstRow
  ): TaxInvoice @fdc_generated(from: "TaxInvoice", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Team` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  team(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Team_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Team_FirstRow
  ): Team @fdc_generated(from: "Team", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UtilityRecord` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  utilityRecord(
    """
    The key used to identify the object.
    """
    key: UtilityRecord_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UtilityRecord_FirstRow
  ): UtilityRecord @fdc_generated(from: "UtilityRecord", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Vehicle` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  vehicle(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Vehicle_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Vehicle_FirstRow
  ): Vehicle @fdc_generated(from: "Vehicle", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `VehicleAssignment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  vehicleAssignment(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: VehicleAssignment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: VehicleAssignment_FirstRow
  ): VehicleAssignment @fdc_generated(from: "VehicleAssignment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `VehicleBillingDocument` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  vehicleBillingDocument(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: VehicleBillingDocument_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: VehicleBillingDocument_FirstRow
  ): VehicleBillingDocument @fdc_generated(from: "VehicleBillingDocument", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `VehicleExpense` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  vehicleExpense(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: VehicleExpense_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: VehicleExpense_FirstRow
  ): VehicleExpense @fdc_generated(from: "VehicleExpense", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Worker` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  worker(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Worker_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Worker_FirstRow
  ): Worker @fdc_generated(from: "Worker", purpose: QUERY_SINGLE)
  """
  ✨ List `Accommodation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  accommodations(
    """
    Filter condition to narrow down the query results.
    """
    where: Accommodation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Accommodation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Accommodation_Having
  ): [Accommodation!]! @fdc_generated(from: "Accommodation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `AccommodationAssignment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  accommodationAssignments(
    """
    Filter condition to narrow down the query results.
    """
    where: AccommodationAssignment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AccommodationAssignment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AccommodationAssignment_Having
  ): [AccommodationAssignment!]! @fdc_generated(from: "AccommodationAssignment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `AccommodationBillingDocument` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  accommodationBillingDocuments(
    """
    Filter condition to narrow down the query results.
    """
    where: AccommodationBillingDocument_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AccommodationBillingDocument_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AccommodationBillingDocument_Having
  ): [AccommodationBillingDocument!]! @fdc_generated(from: "AccommodationBillingDocument", purpose: QUERY_MULTIPLE)
  """
  ✨ List `AccommodationBillingLineItem` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  accommodationBillingLineItems(
    """
    Filter condition to narrow down the query results.
    """
    where: AccommodationBillingLineItem_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AccommodationBillingLineItem_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AccommodationBillingLineItem_Having
  ): [AccommodationBillingLineItem!]! @fdc_generated(from: "AccommodationBillingLineItem", purpose: QUERY_MULTIPLE)
  """
  ✨ List `AdvancePayment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  advancePayments(
    """
    Filter condition to narrow down the query results.
    """
    where: AdvancePayment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AdvancePayment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AdvancePayment_Having
  ): [AdvancePayment!]! @fdc_generated(from: "AdvancePayment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Agent` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  agents(
    """
    Filter condition to narrow down the query results.
    """
    where: Agent_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Agent_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Agent_Having
  ): [Agent!]! @fdc_generated(from: "Agent", purpose: QUERY_MULTIPLE)
  """
  ✨ List `AgentConversation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  agentConversations(
    """
    Filter condition to narrow down the query results.
    """
    where: AgentConversation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AgentConversation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AgentConversation_Having
  ): [AgentConversation!]! @fdc_generated(from: "AgentConversation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `AppUser` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  appUsers(
    """
    Filter condition to narrow down the query results.
    """
    where: AppUser_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AppUser_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AppUser_Having
  ): [AppUser!]! @fdc_generated(from: "AppUser", purpose: QUERY_MULTIPLE)
  """
  ✨ List `AuditLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  auditLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: AuditLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AuditLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AuditLog_Having
  ): [AuditLog!]! @fdc_generated(from: "AuditLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Company` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  companies(
    """
    Filter condition to narrow down the query results.
    """
    where: Company_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Company_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Company_Having
  ): [Company!]! @fdc_generated(from: "Company", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DailyDispatch` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  dailyDispatches(
    """
    Filter condition to narrow down the query results.
    """
    where: DailyDispatch_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DailyDispatch_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DailyDispatch_Having
  ): [DailyDispatch!]! @fdc_generated(from: "DailyDispatch", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DailyReport` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  dailyReports(
    """
    Filter condition to narrow down the query results.
    """
    where: DailyReport_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DailyReport_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DailyReport_Having
  ): [DailyReport!]! @fdc_generated(from: "DailyReport", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DailyReportWorker` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  dailyReportWorkers(
    """
    Filter condition to narrow down the query results.
    """
    where: DailyReportWorker_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DailyReportWorker_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DailyReportWorker_Having
  ): [DailyReportWorker!]! @fdc_generated(from: "DailyReportWorker", purpose: QUERY_MULTIPLE)
  """
  ✨ List `MenuConfig` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  menuConfigs(
    """
    Filter condition to narrow down the query results.
    """
    where: MenuConfig_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MenuConfig_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MenuConfig_Having
  ): [MenuConfig!]! @fdc_generated(from: "MenuConfig", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Payment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  payments(
    """
    Filter condition to narrow down the query results.
    """
    where: Payment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Payment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Payment_Having
  ): [Payment!]! @fdc_generated(from: "Payment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Position` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  positions(
    """
    Filter condition to narrow down the query results.
    """
    where: Position_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Position_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Position_Having
  ): [Position!]! @fdc_generated(from: "Position", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Receivable` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  receivables(
    """
    Filter condition to narrow down the query results.
    """
    where: Receivable_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Receivable_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Receivable_Having
  ): [Receivable!]! @fdc_generated(from: "Receivable", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Setting` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  settings(
    """
    Filter condition to narrow down the query results.
    """
    where: Setting_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Setting_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Setting_Having
  ): [Setting!]! @fdc_generated(from: "Setting", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Site` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  sites(
    """
    Filter condition to narrow down the query results.
    """
    where: Site_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Site_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Site_Having
  ): [Site!]! @fdc_generated(from: "Site", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SmartMemo` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  smartMemos(
    """
    Filter condition to narrow down the query results.
    """
    where: SmartMemo_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SmartMemo_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SmartMemo_Having
  ): [SmartMemo!]! @fdc_generated(from: "SmartMemo", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SmartMemoCategory` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  smartMemoCategories(
    """
    Filter condition to narrow down the query results.
    """
    where: SmartMemoCategory_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SmartMemoCategory_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SmartMemoCategory_Having
  ): [SmartMemoCategory!]! @fdc_generated(from: "SmartMemoCategory", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SystemConfig` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  systemConfigs(
    """
    Filter condition to narrow down the query results.
    """
    where: SystemConfig_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SystemConfig_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SystemConfig_Having
  ): [SystemConfig!]! @fdc_generated(from: "SystemConfig", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SystemLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  systemLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: SystemLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SystemLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SystemLog_Having
  ): [SystemLog!]! @fdc_generated(from: "SystemLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TaxInvoice` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  taxInvoices(
    """
    Filter condition to narrow down the query results.
    """
    where: TaxInvoice_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TaxInvoice_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TaxInvoice_Having
  ): [TaxInvoice!]! @fdc_generated(from: "TaxInvoice", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Team` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  teams(
    """
    Filter condition to narrow down the query results.
    """
    where: Team_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Team_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Team_Having
  ): [Team!]! @fdc_generated(from: "Team", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UtilityRecord` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  utilityRecords(
    """
    Filter condition to narrow down the query results.
    """
    where: UtilityRecord_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UtilityRecord_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UtilityRecord_Having
  ): [UtilityRecord!]! @fdc_generated(from: "UtilityRecord", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Vehicle` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  vehicles(
    """
    Filter condition to narrow down the query results.
    """
    where: Vehicle_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Vehicle_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Vehicle_Having
  ): [Vehicle!]! @fdc_generated(from: "Vehicle", purpose: QUERY_MULTIPLE)
  """
  ✨ List `VehicleAssignment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  vehicleAssignments(
    """
    Filter condition to narrow down the query results.
    """
    where: VehicleAssignment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [VehicleAssignment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: VehicleAssignment_Having
  ): [VehicleAssignment!]! @fdc_generated(from: "VehicleAssignment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `VehicleBillingDocument` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  vehicleBillingDocuments(
    """
    Filter condition to narrow down the query results.
    """
    where: VehicleBillingDocument_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [VehicleBillingDocument_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: VehicleBillingDocument_Having
  ): [VehicleBillingDocument!]! @fdc_generated(from: "VehicleBillingDocument", purpose: QUERY_MULTIPLE)
  """
  ✨ List `VehicleExpense` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  vehicleExpenses(
    """
    Filter condition to narrow down the query results.
    """
    where: VehicleExpense_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [VehicleExpense_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: VehicleExpense_Having
  ): [VehicleExpense!]! @fdc_generated(from: "VehicleExpense", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Worker` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  workers(
    """
    Filter condition to narrow down the query results.
    """
    where: Worker_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Worker_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Worker_Having
  ): [Worker!]! @fdc_generated(from: "Worker", purpose: QUERY_MULTIPLE)
}
