import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, Check, CheckCircle2, Download, FileCheck2, FileSpreadsheet, FolderOpen, Loader2, RotateCcw, Settings2, ShieldCheck, Sparkles, Upload, X } from 'lucide-react';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { ConversionPlan, ConversionResult, Mapping, planSchema, WorkbookFile } from './types';
import { readWorkbook } from './workbook';
import { createDocumentPlan, documentTotals, readSourceDocument, validateAutomaticPlan } from './businessDocuments';
import { validatePlanReferences } from './planning';
import { convertWorkbook } from './writer';
import { listWorks, SavedWork, saveWork } from './storage';
import { MappingEditor, RulesEditor } from './MappingEditor';
import WorkbookPreview from './WorkbookPreview';
import type { WorkspaceProps } from './ConversionWorkspace';
import './conversion.css';
import './simpleConversion.css';

export const DOCUMENT_EXAMPLES = {
  delegation: { label: '위임장', source: '10_현재위임장_가상원본.xlsx', target: '11_타회사위임장_개인별양식.xlsx', expected: '12_위임장_정답예시.xlsx', detail: '작업자 목록 → 한 사람당 위임장 1개' },
  labor: { label: '노임명세서', source: '20_현재노임명세서_2026-09_가상원본.xlsx', target: '21_타회사노임명세서_한줄양식.xlsx', expected: '22_노임명세서_정답예시.xlsx', detail: '한 사람 두 줄 → 다른 회사의 한 줄 양식' },
};
const DEFAULT_INSTRUCTION = '현재 plan의 확정된 연결을 유지하고 미확인 연결만 보완하세요. 대상 양식에 있는 항목만 채우며, 원본에만 있는 날짜 열이나 대상에 없는 수임인 등은 추가할 필요가 없습니다. headerRow/startRow/endRow/fixedCells 주소와 기존 수식을 유지하세요. 입력칸이 부족하면 프로그램이 overflow 규칙으로 양식을 복제하므로 endRow를 늘리거나 인원수를 질문하지 마세요. 기존 금액 수식은 프로그램이 원본 금액과 대조하고 불일치하면 다운로드를 차단하므로 별도 질문이 필요하지 않습니다. 모든 작업자의 원본 공수·금액·지급구분을 유지하고 세금·공제·합산·행 제외를 추가하지 마세요. 개인별 서식은 한 사람당 파일 하나, 표 형식은 한 사람 한 행으로 작성하세요. 서명란을 비우고 원본에 있는 정보와 대상의 항목 의미가 명확하면 confirmed=true, questions=[]로 반환하세요. 실제로 해결되지 않은 항목만 질문하세요.';
const errText = (e: unknown) => e instanceof Error ? e.message : '파일을 처리하지 못했습니다. 다시 확인해 주세요.';
export interface SimpleWorkspaceProps extends WorkspaceProps { checkAi?: () => Promise<{ configured: boolean; model: string; thinkingLevel?: string }>; onAdvanced?: () => void; }

export default function SimpleConversionWorkspace({ ownerId, analyze, checkAi, onAdvanced }: SimpleWorkspaceProps) {
  const [source, setSource] = useState<WorkbookFile>(); const [target, setTarget] = useState<WorkbookFile>();
  const [sourceSheet, setSourceSheet] = useState(''); const [targetSheet, setTargetSheet] = useState('');
  const [prompt, setPrompt] = useState(''); const [plan, setPlan] = useState<ConversionPlan>();
  const [result, setResult] = useState<ConversionResult>(); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const [notice, setNotice] = useState(''); const [ai, setAi] = useState<{ configured: boolean; model: string; thinkingLevel?: string }>(); const [aiError, setAiError] = useState('');
  const [example, setExample] = useState<keyof typeof DOCUMENT_EXAMPLES>(); const [review, setReview] = useState(false); const [accepted, setAccepted] = useState(false);
  const [history, setHistory] = useState<SavedWork[]>([]); const [showHistory, setShowHistory] = useState(false);
  const [usage, setUsage] = useState(''); const controller = useRef<AbortController>(); const currentId = useRef<string>(crypto.randomUUID());
  const sourceState = useMemo(() => { try { return source ? { document: readSourceDocument(source, sourceSheet || source.sheets[0].name), error: '' } : { error: '' }; } catch(e) { return { error: errText(e) }; } }, [source, sourceSheet]);
  const document = sourceState.document; const totals = document ? documentTotals(document.table) : undefined;
  const problems = plan && document ? validatePlanReferences(plan, document.table.fields) : [];
  const mappings = plan ? [...plan.mappings.map((m, i) => ({ mapping: m, index: i, fixed: false })), ...plan.fixedCells.map((f, i) => ({ mapping: f.mapping, index: i, fixed: true }))] : [];
  const needs = mappings.filter(({ mapping: m }) => !m.confirmed || (m.required && m.mode === 'blank'));
  const downloadReady = !!result?.outputs.length && !busy && !result.issues.some(i => i.level === 'error') && (!result.issues.some(i => i.level === 'warning') || accepted);
  const refreshStatus = () => { if (!checkAi) return; setAi(undefined); setAiError(''); checkAi().then(setAi).catch(e => setAiError(errText(e))); };
  useEffect(() => { if (checkAi) checkAi().then(setAi).catch(e => { setAi(undefined); setAiError(errText(e)); }); listWorks(ownerId).then(setHistory).catch(() => setNotice('이 브라우저에서는 작업 이력을 저장할 수 없습니다.')); return () => controller.current?.abort(); }, [ownerId, checkAi]);
  useEffect(() => { if (target && document) setPlan(current => current?.targetId === target.id && current.sheetName === (targetSheet || target.sheets[0].name) ? current : createDocumentPlan(target, document, targetSheet || target.sheets[0].name)); }, [target, targetSheet, document]);
  useEffect(() => { if (!busy) return; const guard = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', guard); return () => window.removeEventListener('beforeunload', guard); }, [busy]);
  const invalidate = () => { setResult(undefined); setReview(false); setAccepted(false); setUsage(''); setError(''); };
  const upload = async (files: FileList | File[] | null, role: 'source' | 'target') => {
    if (!files?.length || busy) return; setBusy('파일을 읽고 있습니다'); setError('');
    try { if(files.length > 1) throw new Error('간편 화면에서는 원본과 양식을 하나씩 선택해 주세요.'); const file = files[0]; const next = await readWorkbook(await file.arrayBuffer(), file.name); invalidate(); setExample(undefined); currentId.current = crypto.randomUUID(); if(role === 'source') { setPlan(undefined); setSource(next); setSourceSheet(next.sheets[0].name); } else { setTarget(next); setTargetSheet(next.sheets[0].name); } }
    catch(e) { setError(errText(e)); } finally { setBusy(''); }
  };
  const loadExample = async (kind: keyof typeof DOCUMENT_EXAMPLES) => {
    setBusy('예시 파일을 준비하고 있습니다'); setError('');
    try { const names = DOCUMENT_EXAMPLES[kind]; const files = await Promise.all([names.source,names.target].map(async name => { const response = await fetch(`/excel-converter/examples/${encodeURIComponent(name)}`); if(!response.ok) throw new Error('예시를 불러오지 못했습니다.'); return readWorkbook(await response.arrayBuffer(),name); })); invalidate(); setSource(files[0]); setTarget(files[1]); setSourceSheet(files[0].sheets[0].name); setTargetSheet(files[1].sheets[0].name); setPrompt(''); setExample(kind); currentId.current = crypto.randomUUID(); setNotice('가상 인원 3명 · 총 7공수 · 금액 1,270,000원으로 테스트합니다.'); }
    catch(e) { setError(errText(e)); } finally { setBusy(''); }
  };
  const updateMapping = (index: number, fixed: boolean, mapping: Mapping) => { if(!plan) return; setResult(undefined); setAccepted(false); setPlan({ ...plan, ...(fixed ? { fixedCells: plan.fixedCells.map((f,i) => i===index ? { ...f,mapping } : f) } : { mappings: plan.mappings.map((m,i) => i===index ? mapping : m) }) }); };
  const finish = async (next: ConversionPlan) => {
    if (!target || !source || !document) return;
    const errors = validatePlanReferences(next, document.table.fields); if(errors.length) { setReview(true); setNotice('AI가 확신하지 못한 항목만 확인해 주세요.'); return; }
    controller.current = new AbortController(); setBusy('새 양식에 작성하고 원본과 대조하고 있습니다');
    const converted = await convertWorkbook(target, next, document.table, setBusy, controller.current.signal);
    if (!prompt.trim() && converted.outputCount !== document.table.rows.length) throw new Error('작업자 수가 달라졌습니다. 원본을 보존하도록 다시 분석해 주세요.');
    setResult(converted); setReview(false); setAccepted(false);
    const work: SavedWork = { id: currentId.current, name: `${document.kind === 'delegation' ? '위임장' : document.kind === 'labor' ? '노임명세서' : '엑셀'} → ${target.name}`, updatedAt: Date.now(), expiresAt: Date.now()+30*86400000, sources: [source], targets: [target], primarySheet: document.sheetName, headerRow: document.headerRow, joins: [], plans: [next], prompt, results: [{ targetId: target.id, result: converted, revision: 1 }], revision: 1, resultRevision: 1, status: 'review', reviewNote: '', appliedPrompts: { [target.id]: prompt } };
    try { await saveWork(ownerId,work); setHistory(await listWorks(ownerId)); } catch { setNotice('변환은 완료했지만 이력 저장에 실패했습니다. 결과 파일을 내려받아 주세요.'); }
  };
  const convert = async (useAi: boolean) => {
    if (!source || !target || !document || !plan || busy) return; setBusy(useAi ? 'Gemini가 양식을 맞추고 있습니다' : '확인한 규칙으로 변환하고 있습니다'); setError(''); setResult(undefined);
    try {
      let next = plan;
      if(useAi) { const response = await analyze(`${DEFAULT_INSTRUCTION}${prompt.trim() ? `\n추가 지시: ${prompt}` : ''}`,plan,document.table,target); next = planSchema.parse(response.plan); if(next.targetId!==target.id || next.sheetName!==plan.sheetName) throw new Error('AI가 다른 양식을 반환했습니다. 다시 시도해 주세요.'); if(!prompt.trim()) validateAutomaticPlan(plan, next); setUsage(`Gemini ${response.model} · ${((response.elapsedMs || 0)/1000).toFixed(1)}초`); }
      setPlan(next); await finish(next);
    } catch(e) { setError(errText(e)); } finally { setBusy(''); }
  };
  const download = async () => { if(!downloadReady || !result) return; if(result.outputs.length===1) { const out=result.outputs[0];saveAs(new Blob([out.bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),out.name); } else { const zip=new JSZip();result.outputs.forEach(o=>zip.file(o.name,o.bytes));saveAs(await zip.generateAsync({type:'blob'}),'변환완료_문서.zip'); } };
  const reset = () => { invalidate(); setSource(undefined); setTarget(undefined); setPlan(undefined); setExample(undefined); setPrompt(''); setNotice(''); currentId.current=crypto.randomUUID(); };
  return <div className="ec-simple">
    <header className="ec-topbar"><div className="ec-logo"><FileSpreadsheet size={20}/><span>문서 양식 변환</span></div><div><button onClick={()=>setShowHistory(!showHistory)} disabled={!!busy}><FolderOpen size={16}/>최근 작업</button>{onAdvanced && <button className="ec-icon-button" onClick={onAdvanced} disabled={!!busy} title="기존 상세 화면"><Settings2 size={17}/><span>상세 화면</span></button>}</div></header>
    <main className="ec-content"><section className={`ec-intro ${source && target ? 'compact' : ''}`}><span className="ec-kicker">복잡한 엑셀 작업을 간단하게</span><h1>{source && target ? '양식 준비가 끝났어요.' : <>파일 두 개만 올리면,<br/>다른 회사 양식으로.</>}</h1><p>위임장도, 노임명세서도. AI가 항목을 찾아 채워드립니다.</p><div className={`ec-ai-status ${ai?.configured?'connected':''}`}><span/>{ai?.configured?`${ai.model.replace('gemini-', 'Gemini ').replace('-flash', ' Flash')} · ${{low:'빠르게',medium:'균형',high:'꼼꼼하게'}[ai.thinkingLevel || 'medium'] || '균형'} 분석`:aiError || (ai?'Gemini 설정이 필요합니다':'Gemini 연결 확인 중')}{(!ai?.configured || aiError) && <><button onClick={refreshStatus}>다시 확인</button></>}<a className="ec-model-settings" href="/settings/ai#excel-conversion-ai">AI 설정</a></div></section>
    {showHistory && <section className="ec-history"><div className="ec-section-heading"><h2>최근 변환</h2><button aria-label="최근 작업 닫기" onClick={()=>setShowHistory(false)}><X size={16}/></button></div>{history.length?history.slice(0,8).map(work=><button className="ec-history-row" key={work.id} disabled={!!busy} onClick={()=>{invalidate();setSource(work.sources[0]);setTarget(work.targets[0]);setSourceSheet(work.primarySheet);setTargetSheet(work.plans[0]?.sheetName||'');setPrompt(work.prompt);setPlan(work.plans[0]);setResult(work.results.find(r=>r.revision===work.revision)?.result);setExample(undefined);currentId.current=work.id;setShowHistory(false);setNotice('저장된 결과를 불러왔습니다. 설정을 수정하면 다시 변환해야 합니다.');}}><FileCheck2 size={17}/><span>{work.name}<small>{new Date(work.updatedAt).toLocaleDateString('ko-KR')}</small></span><ArrowRight size={16}/></button>):<p>변환한 작업이 여기에 저장됩니다.</p>}</section>}
    {!result && !(source && target) && <section className="ec-examples"><div><strong>처음이라면 예시로 시작하세요</strong><span>실제 화면의 항목 구성 · 개인정보는 모두 가상</span></div><div>{Object.entries(DOCUMENT_EXAMPLES).map(([key,item])=><button key={key} disabled={!!busy} onClick={()=>loadExample(key as keyof typeof DOCUMENT_EXAMPLES)}><FileSpreadsheet size={17}/>{item.label} 예시<ArrowRight size={15}/></button>)}</div></section>}
    {(error || sourceState.error) && <div className="ec-alert error" role="alert"><strong>잠깐, 확인이 필요합니다.</strong><p>{error || sourceState.error}</p>{error && <button onClick={()=>setError('')}>닫기</button>}</div>}
    {notice && <div className="ec-alert info" role="status"><span>{notice}</span><button aria-label="안내 닫기" onClick={()=>setNotice('')}><X size={15}/></button></div>}
    <section className="ec-upload-grid"><SimpleUpload title="지금 쓰는 파일" number="1" description="데이터가 들어 있는 우리 회사 엑셀" file={source} busy={!!busy} onFiles={files=>upload(files,'source')} onRemove={()=>{invalidate();setSource(undefined);setPlan(undefined);setExample(undefined);}}/><div className="ec-flow-arrow"><ArrowRight/></div><SimpleUpload title="받을 회사 양식" number="2" description="다른 회사의 빈 엑셀 양식" file={target} busy={!!busy} onFiles={files=>upload(files,'target')} onRemove={()=>{invalidate();setTarget(undefined);setPlan(undefined);setExample(undefined);}}/></section>
    {document && <div className="ec-found"><CheckCircle2 size={17}/><span><strong>{totals?.people}명</strong>을 찾았습니다{totals?.manDays!==undefined && <> · 총 <strong>{totals.manDays}공수</strong></>}{totals?.amount!==undefined && <> · {totals.amountLabel} <strong>{totals.amount.toLocaleString()}원</strong></>}<small>{document.label}</small></span></div>}
    {(source || target) && !result && <WorkbookPreview source={source} target={target}/>}
    {(!result || review) && <section className="ec-instruction"><label htmlFor="ec-instruction">추가로 원하는 내용 <span>선택</span></label><textarea id="ec-instruction" aria-label="추가 요청" rows={2} maxLength={4000} value={prompt} disabled={!!busy} onChange={e=>{invalidate();setPrompt(e.target.value);}} placeholder="비워 두셔도 됩니다. 예: 날짜는 2026.09.30으로, 위임장은 사람별로 만들어 주세요."/><p>인원·공수·금액은 그대로 옮기고, 서명은 새로 확인할 수 있도록 비워 둡니다.</p></section>}
    {review && plan && document && <section className="ec-review"><h2>이 항목만 알려주세요</h2><p>확실하게 연결되지 않은 항목입니다. 사용할 원본을 선택해 주세요.</p>{needs.map(({mapping:m,index,fixed})=><label key={`${fixed}-${index}`}><strong>{m.label}</strong><select aria-label={`${m.label} 연결`} value={m.sourceKeys[0]||''} onChange={e=>updateMapping(index,fixed,{...m,mode:e.target.value?'copy':'blank',sourceKeys:e.target.value?[e.target.value]:[],confirmed:true})}><option value="">빈칸으로 두기</option>{document.table.fields.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select>{!m.required && <button onClick={()=>updateMapping(index,fixed,{...m,mode:'blank',sourceKeys:[],confirmed:true})}>비워 두기</button>}</label>)}{plan.questions.map((q,i)=><div className="ec-question" key={i}><p>{q}</p><button onClick={()=>setPlan({...plan,questions:plan.questions.filter((_,n)=>n!==i)})}>아래 상세 설정에서 확인했습니다</button></div>)}{problems.filter(p=>!p.includes('연결 또는 빈칸')).map((p,i)=><p className="ec-problem" key={i}>{p}</p>)}<button className="ec-primary" disabled={!!busy||!!problems.length} onClick={()=>convert(false)}>확인한 내용으로 변환</button></section>}
    {busy && <div className="ec-progress" role="status"><Loader2 size={22}/><div><strong>{busy}</strong><p>원본을 보존하면서 새 파일을 만들고 있습니다.</p></div></div>}
    {!result && !review && <section className="ec-main-action"><button className="ec-primary ec-convert" disabled={!source||!target||!document||!!sourceState.error||!!busy||!plan} onClick={()=>convert(true)}>{busy?<Loader2 size={20}/>:<Sparkles size={20}/>}AI로 변환하기<ArrowRight size={18}/></button><p>항목 이름과 양식 구조를 분석합니다. 원본의 개인정보·금액 행은 AI로 보내지 않습니다.</p>{example && <button className="ec-text-button" disabled={!!busy||!!prompt.trim()} onClick={()=>convert(false)}>AI 호출 없이 예시 결과 먼저 확인</button>}</section>}
    {result && <section className="ec-result" aria-label="변환 결과"><div className="ec-result-heading"><div className={result.issues.some(i=>i.level==='error')?'error':'success'}><CheckCircle2 size={29}/></div><div><h2>{result.issues.some(i=>i.level==='error')?'수정할 내용을 찾았습니다':'새 양식으로 변환했어요'}</h2><p>{result.outputCount}명 · {result.outputs.length}개 파일{example && ' · 예시 정답은 아래에서 확인할 수 있어요'}</p></div></div>{result.issues.map((issue,i)=><div key={i} className={`ec-alert ${issue.level==='error'?'error':'info'}`}><span>{issue.message}</span></div>)}{!result.issues.length && <p className="ec-checkline"><ShieldCheck size={17}/>파일을 다시 열어 입력한 값과 대조했습니다.</p>}{result.issues.some(i=>i.level==='warning') && <label className="ec-accept"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>위 주의사항을 확인했습니다</label>}<WorkbookPreview source={source} target={target} outputs={result.outputs}/><button className="ec-primary ec-download" disabled={!downloadReady} onClick={download}><Download size={20}/>{result.outputs.length>1?'완성된 파일 모두 받기':'완성된 엑셀 받기'}</button><div className="ec-result-links"><button onClick={()=>{setResult(undefined);setReview(false);}}>작성 내용 수정</button><button onClick={reset}><RotateCcw size={14}/>다른 파일 변환</button></div>{example && <div className="ec-sample-downloads">{['source','target','expected'].map((key,i)=><a key={key} download href={`/excel-converter/examples/${encodeURIComponent(DOCUMENT_EXAMPLES[example][key as 'source'|'target'|'expected'])}`}>{['원본 예시','다른 회사 양식','정답 예시'][i]}<Download size={13}/></a>)}</div>}{usage && <small className="ec-usage">{usage}</small>}</section>}
    {plan && document && <details className="ec-advanced"><summary><Settings2 size={15}/>필요할 때만 상세 설정</summary><p>보통은 수정하지 않아도 됩니다. 항목 연결·작성 범위를 직접 바꾸려면 여기를 사용하세요.</p><div className="ec-settings-grid"><label>원본 시트<select disabled={!!busy} value={sourceSheet} onChange={e=>{invalidate();setPlan(undefined);setSourceSheet(e.target.value);}}>{source?.sheets.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label>대상 시트<select disabled={!!busy} value={targetSheet} onChange={e=>{invalidate();setTargetSheet(e.target.value);}}>{target?.sheets.map(s=><option key={s.name}>{s.name}</option>)}</select></label>{!!plan.mappings.length && <><label>입력 시작 행<input type="number" min={2} value={plan.startRow} disabled={!!busy} onChange={e=>{setResult(undefined);setPlan({...plan,startRow:Number(e.target.value)});}}/></label><label>입력 마지막 행<input type="number" value={plan.endRow} disabled={!!busy} onChange={e=>{setResult(undefined);setPlan({...plan,endRow:Number(e.target.value)});}}/></label></>}</div><fieldset disabled={!!busy} className="ec-settings-body xc-app">{mappings.map(({mapping,index,fixed})=><MappingEditor key={`${fixed}-${index}`} mapping={mapping} fields={document.table.fields} onChange={m=>updateMapping(index,fixed,m)}/>)}<RulesEditor rules={plan.rules} fields={document.table.fields} onChange={rules=>{setResult(undefined);setPlan({...plan,rules});}}/></fieldset><button disabled={!!busy||!!problems.length||!!prompt.trim()} onClick={()=>convert(false)}>직접 설정한 내용으로 변환</button>{prompt.trim() && <p>추가 요청은 위의 AI로 변환하기 버튼으로 적용해 주세요.</p>}</details>}
    <footer className="ec-footer"><ShieldCheck size={16}/><span>원본 파일은 바뀌지 않습니다. 최근 작업은 이 계정의 현재 브라우저에 30일간 보관됩니다.</span></footer>
    </main>
  </div>;
}
function SimpleUpload({ title, description, number, file, busy, onFiles, onRemove }: { title: string; description: string; number: string; file?: WorkbookFile; busy: boolean; onFiles:(files:FileList|File[])=>void; onRemove:()=>void }) {
  const [over,setOver]=useState(false);
  return <section className={`ec-upload-card ${file?'filled':''} ${over?'over':''}`} onDragOver={e=>{e.preventDefault();if(!busy)setOver(true);}} onDragLeave={()=>setOver(false)} onDrop={e=>{e.preventDefault();setOver(false);if(!busy)onFiles(Array.from(e.dataTransfer.files));}}><div className="ec-upload-title"><span>{number}</span><h2>{title}</h2>{file&&<button disabled={busy} aria-label={`${title} 제거`} onClick={onRemove}><X size={17}/></button>}</div><label className="ec-dropzone"><div className="ec-upload-icon">{file?<FileCheck2 size={30}/>:<Upload size={28}/>}</div><strong>{file?file.name:description}</strong><span>{file?'파일을 바꾸려면 클릭하세요':'클릭하거나 파일을 끌어 놓으세요'}</span><input aria-label={title} type="file" accept=".xlsx" disabled={busy} onChange={e=>{if(e.target.files)onFiles(e.target.files);e.target.value='';}}/>{file?<span className="ec-file-ready"><Check size={14}/>준비 완료</span>:<span className="ec-file-type">Excel .xlsx</span>}</label></section>;
}
